POST /rest/evita/Product/query

{
  "head" : [
    {
      "label" : {
        "name" : "query-name",
        "value" : "my-query"
      }
    }
  ],
  "filterBy" : {
    "and" : [
      {
        "entityPrimaryKeyInSet" : [
          1,
          2,
          3
        ],
        "attributeStatusEquals" : "ACTIVE"
      }
    ]
  },
  "orderBy" : [
    {
      "attributeCodeNatural" : "ASC"
    },
    {
      "attributeCatalogNumberNatural" : "DESC"
    }
  ],
  "require" : {
    "entityFetch" : {
      "attributeContentAll" : true,
      "priceContentAll" : true
    },
    "facetSummary" : { }
  }
}