/*
 *
 *                         _ _        ____  ____
 *               _____   _(_) |_ __ _|  _ \| __ )
 *              / _ \ \ / / | __/ _` | | | |  _ \
 *             |  __/\ V /| | || (_| | |_| | |_) |
 *              \___| \_/ |_|\__\__,_|____/|____/
 *
 *   Copyright (c) 2025
 *
 *   Licensed under the Business Source License, Version 1.1 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   https://github.com/FgForrest/evitaDB/blob/master/LICENSE
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package io.evitadb.export.s3;

import io.evitadb.api.configuration.ExportOptions;
import io.evitadb.api.exception.FileForFetchNotFoundException;
import io.evitadb.api.file.FileForFetch;
import io.evitadb.core.executor.DelayedAsyncTask;
import io.evitadb.core.executor.Scheduler;
import io.evitadb.core.management.FileManagementService;
import io.evitadb.dataType.PaginatedList;
import io.evitadb.exception.UnexpectedIOException;
import io.evitadb.export.s3.configuration.S3ExportOptions;
import io.evitadb.spi.export.ExportService;
import io.evitadb.spi.export.model.ExportFileHandle;
import io.evitadb.utils.Assert;
import io.evitadb.utils.CollectionUtils;
import io.evitadb.utils.FileUtils;
import io.evitadb.utils.IOUtils;
import io.evitadb.utils.UUIDUtil;
import io.minio.*;
import io.minio.BucketExistsArgs.Builder;
import io.minio.http.HttpUtils;
import io.minio.messages.Item;
import lombok.extern.slf4j.Slf4j;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

/**
 * Implementation of {@link ExportService} that stores exported files in S3-compatible storage
 * (such as Amazon S3 or MinIO).
 *
 * This implementation uses the MinIO Java client to interact with S3-compatible storage.
 * File metadata is stored as S3 user metadata on each object to avoid separate metadata objects
 * and reduce API calls.
 *
 * @author Jan Novotny (novotny@fg.cz), FG Forrest a.s. (c) 2025
 */
@Slf4j
public class ExportS3Service implements ExportService {

	/**
	 * User metadata key for file ID.
	 */
	private static final String META_FILE_ID = "file-id";

	/**
	 * User metadata key for original file name.
	 */
	private static final String META_NAME = "name";

	/**
	 * User metadata key for file description.
	 */
	private static final String META_DESCRIPTION = "description";

	/**
	 * User metadata key for content type.
	 */
	private static final String META_CONTENT_TYPE = "content-type";

	/**
	 * User metadata key for creation timestamp.
	 */
	private static final String META_CREATED = "created";

	/**
	 * User metadata key for origin tags.
	 */
	private static final String META_ORIGIN = "origin";

	/**
	 * User metadata key for catalog name.
	 */
	private static final String META_CATALOG = "catalog";

	/**
	 * User metadata key for "generated by" tag.
	 */
	private static final String META_GENERATED_BY = "generated-by";

	/**
	 * Value for "generated by" tag.
	 */
	private static final String GENERATED_BY_VALUE = "evitaDB-export-s3";

	/**
	 * Part size for S3 multipart upload (10MB).
	 */
	private static final long PART_SIZE = 10_485_760L;

	/**
	 * Prefix for user metadata keys in S3 objects.
	 */
	private static final String USER_METADATA_PREFIX = "x-amz-meta-";

	/**
	 * S3-specific export configuration options containing all settings.
	 */
	private final S3ExportOptions s3Options;

	/**
	 * MinIO async client for S3 operations.
	 */
	private final MinioAsyncClient minioClient;
	/**
	 * System file management service.
	 */
	private final FileManagementService fileManagementService;
	/**
	 * Task that periodically purges old files from the storage.
	 */
	private final DelayedAsyncTask purgeTask;

	/**
	 * Parses user metadata into a {@link FileForFetch} instance.
	 *
	 * @param userMetadata the S3 object user metadata
	 * @param size         the object size in bytes
	 * @return parsed FileForFetch or null if metadata is invalid
	 */
	@Nullable
	private static FileForFetch parseFileForFetch(@Nonnull Map<String, String> userMetadata, long size) {
		try {
			final String fileIdStr = userMetadata.get(META_FILE_ID);
			final String name = userMetadata.get(META_NAME);
			final String description = userMetadata.get(META_DESCRIPTION);
			final String contentType = userMetadata.get(META_CONTENT_TYPE);
			final String createdStr = userMetadata.get(META_CREATED);
			final String originStr = userMetadata.get(META_ORIGIN);
			final String catalogName = userMetadata.get(META_CATALOG);

			if (fileIdStr == null || name == null || createdStr == null) {
				return null;
			}

			final UUID fileId = UUID.fromString(fileIdStr);
			final OffsetDateTime created = OffsetDateTime.parse(createdStr, DateTimeFormatter.ISO_OFFSET_DATE_TIME);
			final String[] origin = (originStr == null || originStr.isBlank())
				? null
				: Arrays.stream(originStr.split(",")).map(String::trim).toArray(String[]::new);

			return new FileForFetch(
				fileId,
				name,
				(description == null || description.isBlank()) ? null : description,
				contentType != null ? contentType : "application/octet-stream",
				size,
				created,
				origin,
				(catalogName == null || catalogName.isBlank()) ? null : catalogName
			);
		} catch (Exception e) {
			log.error("Failed to parse file metadata", e);
			return null;
		}
	}

	/**
	 * Validates whether the given region string is non-null and not blank.
	 *
	 * @param region the region string to validate; may be null
	 * @return {@code true} if the region is non-null and not blank, {@code false} otherwise
	 */
	private static boolean isRegionValid(@Nullable String region) {
		return region != null && !region.isBlank();
	}

	/**
	 * Checks whether the file is managed by this service (has the correct marker).
	 *
	 * @param userMetadata the file metadata
	 * @return true if managed, false otherwise
	 */
	private static boolean isNotManagedFile(@Nonnull Map<String, String> userMetadata) {
		return !GENERATED_BY_VALUE.equals(userMetadata.get(META_GENERATED_BY));
	}

	/**
	 * Creates a new instance of {@link ExportS3Service}.
	 *
	 * @param exportOptions         the export configuration options
	 * @param scheduler             the scheduler for background tasks
	 * @param fileManagementService file management service
	 */
	public ExportS3Service(
		@Nonnull ExportOptions exportOptions,
		@Nonnull Scheduler scheduler,
		@Nonnull FileManagementService fileManagementService
	) {
		if (!(exportOptions instanceof S3ExportOptions)) {
			throw new IllegalArgumentException(
				"ExportS3Service requires S3ExportOptions but got: " + exportOptions.getClass().getSimpleName()
			);
		}
		this.s3Options = (S3ExportOptions) exportOptions;
		this.fileManagementService = fileManagementService;

		// Initialize MinIO async client
		final MinioAsyncClient.Builder clientBuilder = MinioAsyncClient.builder()
			.endpoint(this.s3Options.getEndpointOrThrowException())
			.credentials(
				this.s3Options.getAccessKeyOrThrowException(),
				this.s3Options.getSecretKeyOrThrowException()
			)
			.httpClient(
				HttpUtils.newDefaultHttpClient(
					this.s3Options.getRequestTimeoutInMillis(),
					this.s3Options.getRequestTimeoutInMillis(),
					this.s3Options.getRequestTimeoutInMillis()
				),
				true
			);

		if (isRegionValid(this.s3Options.getRegion())) {
			clientBuilder.region(this.s3Options.getRegion());
		}

		this.minioClient = clientBuilder.build();

		// Ensure bucket exists
		ensureBucketExists();

		// Schedule automatic purging task
		this.purgeTask = new DelayedAsyncTask(
			null,
			"S3 export file service purging task",
			scheduler,
			this::purgeFiles,
			5, TimeUnit.MINUTES
		);
		this.purgeTask.schedule();
	}

	@Nonnull
	@Override
	public PaginatedList<FileForFetch> listFilesToFetch(
		int page,
		int pageSize,
		@Nonnull Set<String> catalog,
		@Nonnull Set<String> origin
	) {
		final List<FileForFetch> allFiles = new ArrayList<>(pageSize < 1000 ? (page * pageSize + pageSize) : 1000);
		final String bucket = this.s3Options.getBucketOrThrowException();
		final String region = this.s3Options.getRegion();
		final boolean regionSet = isRegionValid(region);

		try {
			final ListObjectsArgs.Builder listObjectsBuilder = ListObjectsArgs.builder()
				.bucket(bucket)
				.includeUserMetadata(true)
				.recursive(true);
			if (regionSet) {
				listObjectsBuilder.region(region);
			}

			final Iterable<Result<Item>> objects = this.minioClient.listObjects(listObjectsBuilder.build());

			for (final Result<Item> itemResult : objects) {
				try {
					final Item item = itemResult.get();
					final Map<String, String> userMetadata = getItemUserMetadata(item, bucket);
					if (!userMetadata.isEmpty()) {
						if (isNotManagedFile(userMetadata)) {
							continue;
						}
						final FileForFetch file = parseFileForFetch(userMetadata, item.size());
						if (file == null) {
							continue;
						}

						// Filter by catalog
						boolean catalogMatches = catalog.isEmpty();
						if (!catalogMatches) {
							// If catalog filter is present, file must have a matching catalog name
							// Files in root (null catalog) won't match any specific catalog filter
							catalogMatches = file.catalogName() != null && catalog.contains(file.catalogName());
						}

						if (!catalogMatches) {
							continue;
						}

						// Filter by origin
						boolean originMatches = origin.isEmpty();
						if (!originMatches) {
							final String[] fileOrigin = file.origin();
							if (fileOrigin != null) {
								for (final String o : fileOrigin) {
									if (origin.contains(o)) {
										originMatches = true;
										break;
									}
								}
							}
						}

						if (originMatches) {
							allFiles.add(file);
						}
					}
				} catch (Exception e) {
					log.warn("Failed to process S3 object during listing", e);
				}
			}
		} catch (Exception e) {
			throw new UnexpectedIOException(
				"Failed to list files from S3: " + e.getMessage(),
				"Failed to list files from S3.",
				e
			);
		}

		// Sort by creation date (newest first)
		allFiles.sort(Comparator.comparing(FileForFetch::created).reversed());

		final int firstItem = PaginatedList.getFirstItemNumberForPage(page, pageSize);
		final int totalSize = allFiles.size();
		final int endIndex = Math.min(firstItem + pageSize, totalSize);

		final List<FileForFetch> filePage;
		if (firstItem >= totalSize) {
			filePage = List.of();
		} else {
			filePage = allFiles.subList(firstItem, endIndex);
		}

		return new PaginatedList<>(
			page, pageSize,
			totalSize,
			filePage
		);
	}

	@Nonnull
	@Override
	public Optional<FileForFetch> getFile(@Nonnull UUID fileId) {
		final String bucket = this.s3Options.getBucketOrThrowException();
		final String region = this.s3Options.getRegion();
		final boolean regionSet = isRegionValid(region);

		try {
			final ListObjectsArgs.Builder listObjectsBuilder = ListObjectsArgs.builder()
				.bucket(bucket)
				.prefix(fileId.toString())
				.includeUserMetadata(true)
				.recursive(true);
			if (regionSet) {
				listObjectsBuilder.region(region);
			}

			final Iterable<Result<Item>> objects = this.minioClient.listObjects(listObjectsBuilder.build());

			for (final Result<Item> itemResult : objects) {
				final Item item = itemResult.get();
				final Map<String, String> userMetadata = getItemUserMetadata(item, bucket);
				if (isNotManagedFile(userMetadata)) {
					continue;
				}
				final FileForFetch file = parseFileForFetch(userMetadata, item.size());
				if (file != null && file.fileId().equals(fileId)) {
					return Optional.of(file);
				}
			}
		} catch (Exception e) {
			log.warn("Failed to fetch file metadata for ID: {}", fileId, e);
		}

		return Optional.empty();
	}

	@Nonnull
	@Override
	public ExportFileHandle storeFile(
		@Nonnull String fileName,
		@Nullable String description,
		@Nonnull String contentType,
		@Nullable String catalog,
		@Nullable String origin
	) {
		final UUID fileId = UUIDUtil.randomUUID();
		final String objectKey = fileId + FileUtils.getFileExtension(fileName).map(it -> "." + it).orElse("");
		final OffsetDateTime created = OffsetDateTime.now();

		// Prepare user metadata
		final Map<String, String> userMetadata = CollectionUtils.createHashMap(8);
		userMetadata.put(META_FILE_ID, fileId.toString());
		userMetadata.put(META_NAME, fileName);
		userMetadata.put(META_DESCRIPTION, description != null ? description : "");
		userMetadata.put(META_CONTENT_TYPE, contentType);
		userMetadata.put(META_CREATED, created.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME));
		userMetadata.put(META_ORIGIN, origin != null ? origin : "");
		userMetadata.put(META_CATALOG, catalog != null ? catalog : "");
		userMetadata.put(META_GENERATED_BY, GENERATED_BY_VALUE);

		// Parse origin tags
		final String[] originTags = origin == null ? null : Arrays.stream(origin.split(","))
			.map(String::trim)
			.toArray(String[]::new);

		final CompletableFuture<FileForFetch> fileForFetchFuture = new CompletableFuture<>();

		// Create output stream that buffers data and uploads to S3 when closed
		final S3UploadOutputStream uploadOutputStream = new S3UploadOutputStream(
			this.fileManagementService.createTempFile(fileId.toString()),
			this.minioClient,
			this.s3Options.getBucketOrThrowException(),
			this.s3Options.getRegion(),
			objectKey,
			contentType,
			userMetadata,
			fileId,
			fileName,
			description,
			created,
			originTags,
			catalog,
			fileForFetchFuture,
			this.s3Options.getRequestTimeoutInMillis()
		);

		return new ExportFileHandleS3(
			fileId,
			fileForFetchFuture,
			objectKey,
			uploadOutputStream
		);
	}

	@Nonnull
	@Override
	public InputStream fetchFile(@Nonnull UUID fileId) throws FileForFetchNotFoundException {
		final FileForFetch file = getFile(fileId)
			.orElseThrow(() -> new FileForFetchNotFoundException(fileId));

		final String objectKey = fileId + FileUtils.getFileExtension(file.name()).map(it -> "." + it).orElse("");

		try {
			final long timeout = this.s3Options.getRequestTimeoutInMillis();
			final GetObjectArgs.Builder getObjectBuilder = GetObjectArgs.builder()
				.bucket(this.s3Options.getBucketOrThrowException())
				.object(objectKey);
			final String region = this.s3Options.getRegion();
			if (isRegionValid(region)) {
				getObjectBuilder.region(region);
			}
			return this.minioClient.getObject(
				getObjectBuilder.build()
			).get(timeout, TimeUnit.MILLISECONDS);
		} catch (Exception e) {
			throw new UnexpectedIOException(
				"Failed to fetch file from S3: " + e.getMessage(),
				"Failed to fetch file from S3.",
				e
			);
		}
	}

	@Override
	public void deleteFile(@Nonnull UUID fileId) throws FileForFetchNotFoundException {
		final String bucket = this.s3Options.getBucketOrThrowException();
		final String region = this.s3Options.getRegion();
		final boolean regionSet = isRegionValid(region);

		String objectKey = null;

		try {
			final ListObjectsArgs.Builder listObjectsBuilder = ListObjectsArgs.builder()
				.bucket(bucket)
				.prefix(fileId.toString())
				.includeUserMetadata(true)
				.recursive(true);
			if (regionSet) {
				listObjectsBuilder.region(region);
			}

			final Iterable<Result<Item>> objects = this.minioClient.listObjects(listObjectsBuilder.build());

			for (final Result<Item> itemResult : objects) {
				final Item item = itemResult.get();
				final Map<String, String> userMetadata = getItemUserMetadata(item, bucket);

				final FileForFetch file = parseFileForFetch(userMetadata, item.size());
				if (file != null && file.fileId().equals(fileId)) {
					if (isNotManagedFile(userMetadata)) {
						throw new UnexpectedIOException(
							"File with ID " + fileId + " exists but is not managed by this service (missing marker).",
							"File is not managed by evitaDB export S3 service."
						);
					}
					objectKey = item.objectName();
					break;
				}
			}
		} catch (UnexpectedIOException e) {
			throw e;
		} catch (Exception e) {
			log.warn("Failed to search for S3 object to delete for ID: {}", fileId, e);
		}

		if (objectKey == null) {
			// the file is already not present - nothing to delete
			return;
		}

		try {
			final long timeout = this.s3Options.getRequestTimeoutInMillis();
			// If someone else already deleted the object, the operation should be idempotent and not fail
			final RemoveObjectArgs.Builder removeObjectArgsBuilder = RemoveObjectArgs.builder()
				.bucket(bucket)
				.object(objectKey);
			if (regionSet) {
				removeObjectArgsBuilder.region(region);
			}
			this.minioClient.removeObject(
				removeObjectArgsBuilder.build()
			).get(timeout, TimeUnit.MILLISECONDS);
		} catch (Exception e) {
			log.warn(
				"Failed to delete S3 object {}: {}", objectKey,
				e.getMessage()
			);
		}
	}

	@Override
	public long purgeFiles() {
		final OffsetDateTime thresholdDate = OffsetDateTime.now().minusSeconds(
			this.s3Options.getHistoryExpirationSeconds()
		);
		purgeFiles(thresholdDate);
		return 0L;
	}

	@Override
	public void purgeFiles(@Nonnull OffsetDateTime thresholdDate) {
		final String bucket = this.s3Options.getBucketOrThrowException();
		final String region = this.s3Options.getRegion();
		final boolean regionSet = isRegionValid(region);

		final List<FileForFetch> allFiles = new ArrayList<>();

		try {
			String startAfter = null;
			int counter = 0;
			do {
				final ListObjectsArgs.Builder listObjectsBuilder = ListObjectsArgs.builder()
					.bucket(bucket)
					.includeUserMetadata(true)
					.recursive(true);
				if (regionSet) {
					listObjectsBuilder.region(region);
				}
				if (startAfter != null) {
					listObjectsBuilder.startAfter(startAfter);
				}

				final Iterable<Result<Item>> objects = this.minioClient.listObjects(listObjectsBuilder.build());
				boolean empty = true;
				boolean advanced = false;

				for (final Result<Item> itemResult : objects) {
					empty = false;
					try {
						final Item item = itemResult.get();
						startAfter = item.objectName();
						advanced = true;
						final Map<String, String> userMetadata = getItemUserMetadata(item, bucket);
						if (!userMetadata.isEmpty()) {
							if (isNotManagedFile(userMetadata)) {
								continue;
							}
							final FileForFetch file = parseFileForFetch(userMetadata, item.size());
							if (file != null) {
								// Check age expiration
								if (file.created().isBefore(thresholdDate)) {
									log.info("Purging file from S3, because it has been created before {}: {}", thresholdDate, file);
									deleteFile(file.fileId());
								} else {
									// Keep for size check
									allFiles.add(file);
								}
							}
						}
					} catch (Exception e) {
						log.warn("Failed to process S3 object during purging", e);
					}
				}

				if (empty || !advanced) {
					break;
				}
			} while (counter++ < 1_000); // safety limit to avoid infinite loops

			// Check total size and delete oldest files if over limit
			long totalSize = 0L;
			for (FileForFetch fileForFetch : allFiles) {
				totalSize += fileForFetch.totalSizeInBytes();
			}

			if (totalSize > this.s3Options.getSizeLimitBytes()) {
				// Sort by creation date (oldest first) for deletion
				allFiles.sort(Comparator.comparing(FileForFetch::created));

				long savedSize = 0L;
				for (final FileForFetch file : allFiles) {
					log.info("Purging the oldest file from S3, because the storage grew too big: {}", file);
					try {
						final long fileSize = file.totalSizeInBytes();
						deleteFile(file.fileId());
						savedSize += fileSize;
						if (totalSize - savedSize <= this.s3Options.getSizeLimitBytes()) {
							break;
						}
					} catch (Exception e) {
						log.error("Failed to purge file from S3: {}", file, e);
					}
				}
			}

		} catch (Exception e) {
			log.error("Failed to list files from S3 for purging", e);
		}
	}

	@Override
	public void close() throws IOException {
		IOUtils.closeQuietly(
			this.purgeTask::close,
			this.minioClient::close
		);
	}


	/**
	 * Ensures the configured S3 bucket exists, creating it if necessary.
	 */
	private void ensureBucketExists() {
		final String bucket = this.s3Options.getBucketOrThrowException();
		final String region = this.s3Options.getRegion();
		final boolean regionSet = isRegionValid(region);
		try {
			final long timeout = this.s3Options.getRequestTimeoutInMillis();
			final Builder bucketExistsBuilder = BucketExistsArgs.builder().bucket(bucket);
			if (regionSet) {
				bucketExistsBuilder.region(region);
			}
			final boolean bucketExists = this.minioClient.bucketExists(
				bucketExistsBuilder.build()
			).get(timeout, TimeUnit.MILLISECONDS);

			if (!bucketExists) {
				final MakeBucketArgs.Builder makeBucketBuilder = MakeBucketArgs.builder().bucket(bucket);
				if (regionSet) {
					makeBucketBuilder.region(region);
				}
				this.minioClient.makeBucket(
					makeBucketBuilder.build()
				).get(timeout, TimeUnit.MILLISECONDS);
				log.info("Created S3 bucket: {}", bucket);
			}
		} catch (Exception e) {
			throw new UnexpectedIOException(
				"Failed to ensure S3 bucket `" + bucket + "`" + (regionSet ?
					" in region `" + region + "`" :
					"") + " exists: " + e.getMessage(),
				"Failed to ensure S3 bucket exists.",
				e
			);
		}
	}

	/**
	 * Retrieves the user-defined metadata for the specified S3 object. If the object already contains
	 * user metadata, it is returned directly. Otherwise, performs a metadata lookup using the S3 client.
	 *
	 * @param item   the S3 object item for which metadata is to be retrieved; must not be null
	 * @param bucket the name of the S3 bucket containing the object; must not be null
	 * @return a map containing the user-defined metadata for the specified S3 object;
	 * returns an empty map if metadata cannot be retrieved
	 */
	@Nonnull
	private Map<String, String> getItemUserMetadata(
		@Nonnull Item item,
		@Nonnull String bucket
	) {
		try {
			final String region = this.s3Options.getRegion();
			final long timeout = this.s3Options.getRequestTimeoutInMillis();
			final Map<String, String> userMetadata;
			if (item.userMetadata() != null && !item.userMetadata().isEmpty()) {
				userMetadata = normalizeMetadataNames(item.userMetadata());
			} else {
				final StatObjectArgs.Builder statObjectArgsBuilder = StatObjectArgs.builder()
					.bucket(bucket)
					.object(item.objectName());
				if (isRegionValid(region)) {
					statObjectArgsBuilder.region(region);
				}
				final StatObjectResponse statObjectResponse = this.minioClient.statObject(
					statObjectArgsBuilder.build()
				).get(timeout, TimeUnit.MILLISECONDS);
				userMetadata = normalizeMetadataNames(statObjectResponse.userMetadata());
			}
			return userMetadata;
		} catch (Exception e) {
			log.error("Failed to get user metadata for S3 object: {}", item.objectName(), e);
			return Map.of();
		}
	}

	/**
	 * Normalizes the keys of the user metadata map. This method converts keys that
	 * start with a defined prefix to lowercase and removes the prefix. If no keys
	 * match the prefix, the input map remains unchanged.
	 *
	 * @param userMetadata a map containing user-defined metadata where the keys are
	 *                     strings and the values represent metadata values; must not
	 *                     be null.
	 * @return a normalized map of metadata with processed keys, or null if no keys
	 *         required normalization.
	 */
	@Nonnull
	private static Map<String, String> normalizeMetadataNames(@Nonnull Map<String, String> userMetadata) {
		Map<String, String> normalizedMetadata = null;
		for (Map.Entry<String, String> entry : userMetadata.entrySet()) {
			final String key = entry.getKey();
			final String lowerCaseKey = key.toLowerCase(Locale.US);
			if (lowerCaseKey.startsWith(USER_METADATA_PREFIX) || !key.equals(lowerCaseKey)) {
				if (normalizedMetadata == null) {
					normalizedMetadata = CollectionUtils.createHashMap(userMetadata.size());
					// copy previous entries
					for (Map.Entry<String, String> e : userMetadata.entrySet()) {
						if (e.getKey().equals(key)) {
							break;
						}
						normalizedMetadata.put(e.getKey().toLowerCase(Locale.US), e.getValue());
					}
				}
				normalizedMetadata.put(lowerCaseKey.substring(USER_METADATA_PREFIX.length()), entry.getValue());
			}
		}
		return normalizedMetadata != null ? normalizedMetadata : userMetadata;
	}

	/**
	 * Record that contains output stream the export file can be written to and future that will be
	 * completed when the file is uploaded to S3.
	 *
	 * @param fileId             ID of the file
	 * @param fileForFetchFuture Future that will be completed when the file is uploaded
	 * @param objectKey          S3 object key
	 * @param outputStream       Output stream the file can be written to
	 */
	public record ExportFileHandleS3(
		@Nonnull UUID fileId,
		@Nonnull CompletableFuture<FileForFetch> fileForFetchFuture,
		@Nonnull String objectKey,
		@Nonnull S3UploadOutputStream outputStream
	) implements ExportFileHandle {

		@Override
		public long size() {
			return this.outputStream.size();
		}

		@Override
		public void close() throws IOException {
			this.outputStream.close();
		}

		@Nonnull
		@Override
		public String toString() {
			return "s3://" + this.objectKey + " (fileId: " + this.fileId + ")";
		}
	}

	/**
	 * An implementation of OutputStream that writes data to a temporary file and uploads it to an S3-compatible storage
	 * upon stream closure. This class is designed to facilitate stream-based file uploads while managing metadata and
	 * ensuring temporary file cleanup.
	 *
	 * This output stream writes data to a local temporary file and uploads the file to a S3 bucket on close. The class
	 * also supports metadata handling for the uploaded object and returns a `FileForFetch` object upon successful upload.
	 *
	 * Thread Safety: This class is not thread-safe, and instances should not be shared between threads.
	 */
	private static final class S3UploadOutputStream extends OutputStream {
		private final OutputStream delegate;
		private final Path path;
		private final MinioAsyncClient minioClient;
		private final String bucket;
		private final String region;
		private final String objectKey;
		private final String contentType;
		private final Map<String, String> userMetadata;
		private final UUID fileId;
		private final String fileName;
		private final String description;
		private final OffsetDateTime created;
		private final String[] originTags;
		private final String catalogName;
		private final CompletableFuture<FileForFetch> fileForFetchFuture;
		private final long requestTimeoutInMillis;
		private boolean closed;

		S3UploadOutputStream(
			@Nonnull Path tempFilePath,
			@Nonnull MinioAsyncClient minioClient,
			@Nonnull String bucket,
			@Nullable String region,
			@Nonnull String objectKey,
			@Nonnull String contentType,
			@Nonnull Map<String, String> userMetadata,
			@Nonnull UUID fileId,
			@Nonnull String fileName,
			@Nullable String description,
			@Nonnull OffsetDateTime created,
			@Nullable String[] originTags,
			@Nullable String catalogName,
			@Nonnull CompletableFuture<FileForFetch> fileForFetchFuture,
			long requestTimeoutInMillis
		) {
			try {
				final File theFile = tempFilePath.toFile();
				if (!theFile.exists()) {
					Assert.isPremiseValid(
						theFile.createNewFile(),
						"Failed to create temporary file for S3 upload."
					);
				}
				this.delegate = new BufferedOutputStream(new FileOutputStream(theFile));
			} catch (IOException e) {
				throw new UnexpectedIOException(
					"Failed to create temporary file for S3 upload: " + e.getMessage(),
					"Failed to create temporary file for S3 upload.",
					e
				);
			}
			this.path = tempFilePath;
			this.minioClient = minioClient;
			this.bucket = bucket;
			this.region = region;
			this.objectKey = objectKey;
			this.contentType = contentType;
			this.userMetadata = userMetadata;
			this.fileId = fileId;
			this.fileName = fileName;
			this.description = description;
			this.created = created;
			this.originTags = originTags;
			this.catalogName = catalogName;
			this.fileForFetchFuture = fileForFetchFuture;
			this.requestTimeoutInMillis = requestTimeoutInMillis;
			this.closed = false;
		}

		@Override
		public void write(int b) throws IOException {
			this.delegate.write(b);
		}

		@Override
		public void write(@Nonnull byte[] b) throws IOException {
			this.delegate.write(b);
		}

		@Override
		public void write(@Nonnull byte[] b, int off, int len) throws IOException {
			this.delegate.write(b, off, len);
		}

		@Override
		public void flush() throws IOException {
			this.delegate.flush();
		}

		@Override
		public void close() {
			if (this.closed) {
				return;
			}
			this.closed = true;

			try {
				// Ensure all buffered content is written to temporary file
				this.delegate.close();

				// Prepare upload resources
				final File tmpFile = this.path.toFile();
				final long tmpFileSize = tmpFile.length();
				final BufferedInputStream bis = new BufferedInputStream(new FileInputStream(tmpFile));
				final PutObjectArgs.Builder putObjectArgsBuilder = PutObjectArgs.builder()
					.bucket(this.bucket)
					.object(this.objectKey)
					.stream(bis, tmpFileSize, PART_SIZE)
					.contentType(this.contentType)
					.userMetadata(this.userMetadata);
				if (isRegionValid(this.region)) {
					putObjectArgsBuilder.region(this.region);
				}

				// Start async upload, complete the future and clean resources on completion
				this.minioClient
					.putObject(putObjectArgsBuilder.build())
					.orTimeout(this.requestTimeoutInMillis, TimeUnit.MILLISECONDS)
					.whenComplete((ignored, throwable) -> {
						try {
							if (throwable == null) {
								final FileForFetch fileForFetch = new FileForFetch(
									this.fileId,
									this.fileName,
									this.description,
									this.contentType,
									tmpFileSize,
									this.created,
									this.originTags,
									this.catalogName
								);
								this.fileForFetchFuture.complete(fileForFetch);
							} else {
								log.error("Failed to upload file to S3: {}", this.objectKey, throwable);
								final UnexpectedIOException exception = new UnexpectedIOException(
									"Failed to upload file to S3: " + throwable.getMessage(),
									"Failed to upload file to S3.",
									throwable
								);
								this.fileForFetchFuture.completeExceptionally(exception);
							}
						} finally {
							// Close the upload stream and delete temporary file
							IOUtils.closeQuietly(
								bis::close,
								() -> FileUtils.deleteFileIfExists(this.path)
							);
						}
					});
			} catch (Exception e) {
				log.error("Failed to initiate upload to S3: {}", this.objectKey, e);
				final UnexpectedIOException exception = new UnexpectedIOException(
					"Failed to upload file to S3: " + e.getMessage(),
					"Failed to upload file to S3.",
					e
				);
				this.fileForFetchFuture.completeExceptionally(exception);
				// Best-effort cleanup when async upload hasn't started
				IOUtils.closeQuietly(() -> FileUtils.deleteFileIfExists(this.path));
			}
		}

		/**
		 * Returns the size of the file represented by the output stream.
		 *
		 * @return The size of the file in bytes.
		 */
		public long size() {
			return this.path.toFile().length();
		}
	}

}
