POST /rest/evita/product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "audio"
      }
    }
  },
  "require" : {
    "hierarchyCategoriesOfReference" : {
      "emptyHierarchicalEntityBehaviour" : "REMOVE_EMPTY",
      "requirements" : [
        {
          "parents" : {
            "outputName" : "parent",
            "entityFetch" : {
              "attributeContent" : [
                "code"
              ]
            },
            "requirements" : {
              "stopAt" : {
                "distance" : 1
              },
              "statistics" : {
                "statisticsBase" : "WITHOUT_USER_FILTER",
                "statisticsType" : [
                  "CHILDREN_COUNT",
                  "QUERIED_ENTITY_COUNT"
                ]
              }
            }
          }
        }
      ]
    }
  }
}