POST /rest/test-catalog/brand/list

{
  "filterBy": {
    "attributeNameStartsWith": "A"
  },
  "orderBy": {
    "attributeNameNatural": "ASC"
  },
  "require": {
    "entityFetch": {
      "attributeContentAll": true,
      "associatedDataContentAll": true,
      "referenceContentAllWithAttributes": {},
      "dataInLocales": []
    }
  }
}