POST /rest/evita/brand/list

{
  "filterBy": {
    "attributeNameStartsWith": "A",
    "entityLocaleEquals": "en"
  },
  "orderBy": {
    "attributeNameNatural": "ASC"
  },
  "require": {
    "entityFetch": {
      "attributeContentAll": true,
      "hierarchyContent": {},
      "associatedDataContentAll": true,
      "priceContentAll": true,
      "referenceContentAll": true,
      "dataInLocales": []
    }
  }
}