version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    exclude-paths:
      - "data/**"
      - "docker/**"
      - "documentation/**"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"