/*
 *
 *                         _ _        ____  ____
 *               _____   _(_) |_ __ _|  _ \| __ )
 *              / _ \ \ / / | __/ _` | | | |  _ \
 *             |  __/\ V /| | || (_| | |_| | |_) |
 *              \___| \_/ |_|\__\__,_|____/|____/
 *
 *   Copyright (c) 2023-2024
 *
 *   Licensed under the Business Source License, Version 1.1 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   https://github.com/FgForrest/evitaDB/blob/master/LICENSE
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package io.evitadb.api.proxy;

import javax.annotation.Nonnull;

/**
 * Abstract superinterface for all EvitaDB proxy types that wrap sealed entities or entity references.
 *
 * This interface serves as a marker interface for proxy instances dynamically generated by {@link ProxyFactory}
 * using the Proxycian library (ByteBuddy-based). Proxies enable client applications to work with custom
 * POJOs, records, or interfaces instead of the generic {@link io.evitadb.api.requestResponse.data.SealedEntity}
 * API.
 *
 * **Implementation Details:**
 *
 * All proxy instances implement this interface and maintain a reference to their original proxy class definition
 * (the interface or class provided by the client application). This metadata is essential for the proxy
 * infrastructure to correctly handle type conversions, nested proxies, and reference resolution.
 *
 * **Key Subtypes:**
 * - {@link SealedEntityProxy}: Proxies that wrap complete sealed entities
 * - {@link SealedEntityReferenceProxy}: Proxies that wrap entity references with attributes
 *
 * @author Jan Novotný (novotny@fg.cz), FG Forrest a.s. (c) 2023
 */
interface EvitaProxy {

	/**
	 * Returns the original proxy class that was used to create this proxy instance.
	 *
	 * The proxy class is the client-defined interface, abstract class, or POJO class passed to
	 * {@link ProxyFactory#createEntityProxy} or {@link ProxyReferenceFactory#createEntityReferenceProxy}.
	 * The returned class serves as the contract definition for the proxy behavior.
	 *
	 * @return the original client-defined proxy class (never a dynamically generated class)
	 */
	@Nonnull
	Class<?> getProxyClass();

}
