{
  queryProduct(
    filterBy: {
      attributeCodeStartsWith: "garmin"
    },
    orderBy: [
      {
        attributeCodeNatural: ASC
      }
    ]
  ) {
    recordPage {
      data {
        primaryKey
      }
    }
    extraResults {
      queryTelemetry {
        level
        operation
        start
        arguments
        spentTime
        formattedSpentTime
        selfTime
        formattedSelfTime
        stepsCount
        startedAt
        metrics {
          estimatedCardinality
          actualCardinality
          estimatedCost
          actualCost
          recordsReturned
          ioFetchCount
          ioFetchedSizeBytes
          prefetched
        }
      }
    }
  }
}