POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeCodeStartsWith" : "garmin"
  },
  "orderBy" : [
    {
      "attributeCodeNatural" : "ASC"
    }
  ],
  "require" : {
    "queryTelemetry" : true
  }
}