POST /rest/evita/Product/query

{
  "require" : {
    "hierarchyCategoriesOfReference" : {
      "emptyHierarchicalEntityBehaviour" : "REMOVE_EMPTY",
      "requirements" : [
        {
          "fromNode" : {
            "outputName" : "dynamicMenuSubcategories",
            "node" : {
              "filterBy" : {
                "entityPrimaryKeyInSet" : [
                  66482
                ]
              }
            },
            "entityFetch" : {
              "attributeContent" : [
                "code"
              ]
            },
            "requirements" : {
              "stopAt" : {
                "distance" : 1
              },
              "statistics" : {
                "statisticsBase" : "WITHOUT_USER_FILTER",
                "statisticsType" : [
                  "CHILDREN_COUNT"
                ]
              }
            }
          }
        }
      ]
    },
    "page" : {
      "number" : 1,
      "size" : 0
    }
  }
}