POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "accessories"
      },
      "with" : {
        "having" : [
          {
            "attributeStatusEquals" : "ACTIVE"
          }
        ]
      }
    }
  },
  "require" : {
    "hierarchyCategoriesOfReference" : {
      "requirements" : [
        {
          "fromRoot" : {
            "outputName" : "topLevel",
            "entityFetch" : {
              "attributeContent" : [
                "code"
              ]
            },
            "requirements" : {
              "stopAt" : {
                "level" : 2
              }
            }
          }
        }
      ]
    }
  }
}