POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "accessories"
      },
      "with" : {
        "having" : [
          {
            "or" : [
              {
                "attributeValidityIs" : "NULL"
              },
              {
                "attributeValidityInRange" : "2023-12-05T12:00:00Z"
              }
            ]
          }
        ]
      }
    }
  },
  "require" : {
    "hierarchyCategoriesOfReference" : {
      "emptyHierarchicalEntityBehaviour" : "REMOVE_EMPTY",
      "requirements" : [
        {
          "fromRoot" : {
            "outputName" : "topLevel",
            "entityFetch" : {
              "attributeContent" : [
                "code"
              ]
            },
            "requirements" : {
              "stopAt" : {
                "level" : 2
              }
            }
          }
        }
      ]
    }
  }
}