POST /rest/evita/Brand/query

{
  "filterBy" : {
    "entityPrimaryKeyInSet" : [
      64703
    ],
    "entityLocaleEquals" : "en"
  },
  "require" : {
    "entityFetch" : {
      "associatedDataContent" : [
        "allActiveUrls",
        "localization"
      ]
    }
  }
}