POST /rest/evita/Brand/query

{
  "filterBy" : {
    "entityPrimaryKeyInSet" : [
      64703
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "name"
      ],
      "dataInLocales" : [
        "cs"
      ]
    }
  }
}