POST /rest/evita/Product/query

{
  "filterBy" : {
    "entityPrimaryKeyInSet" : [
      105703
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceParameterValuesContentWithAttributes" : {
        "attributeContent" : [
          "variant"
        ],
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        },
        "entityGroupFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      }
    }
  }
}