POST /rest/evita/product/query

{
  "filterBy" : {
    "entityPrimaryKeyInSet" : [
      105703
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceContentAllWithAttributes" : { }
    }
  }
}