POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeCodeEquals" : "samsung-galaxy-watch-4"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceGroupsContent" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ],
          "referenceTagsContent" : {
            "entityFetch" : {
              "attributeContent" : [
                "code"
              ],
              "referenceCategoriesContent" : { }
            }
          }
        }
      }
    }
  }
}