POST /rest/evita/product/query

{
  "filterBy" : {
    "entityPrimaryKeyInSet" : [
      103885
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceBrandContent" : { },
      "referenceCategoriesContent" : { }
    }
  }
}