/*
 *
 *                         _ _        ____  ____
 *               _____   _(_) |_ __ _|  _ \| __ )
 *              / _ \ \ / / | __/ _` | | | |  _ \
 *             |  __/\ V /| | || (_| | |_| | |_) |
 *              \___| \_/ |_|\__\__,_|____/|____/
 *
 *   Copyright (c) 2023-2026
 *
 *   Licensed under the Business Source License, Version 1.1 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   https://github.com/FgForrest/evitaDB/blob/master/LICENSE
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package io.evitadb.index;

import io.evitadb.api.requestResponse.data.mutation.reference.ReferenceKey;
import io.evitadb.api.requestResponse.data.structure.RepresentativeReferenceKey;
import io.evitadb.dataType.Scope;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for {@link EntityIndexKey} focusing on the {@link Comparable} contract consistency with
 * {@link Object#equals(Object)}.
 *
 * @author Generated for evitaDB
 */
@DisplayName("EntityIndexKey compareTo/equals consistency")
class EntityIndexKeyTest {

	@Nested
	@DisplayName("compareTo must be consistent with equals")
	class CompareToConsistency {

		@Test
		@DisplayName("REFERENCED_ENTITY_TYPE keys with different scopes should not compare as equal")
		void shouldDistinguishReferencedEntityTypeKeysByScope() {
			final EntityIndexKey liveKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.LIVE, "CATEGORY"
			);
			final EntityIndexKey archivedKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.ARCHIVED, "CATEGORY"
			);

			// equals() already considers scope (auto-generated by record)
			assertNotEquals(liveKey, archivedKey, "equals() should distinguish different scopes");

			// compareTo() must also distinguish them (Comparable contract)
			assertNotEquals(
				0, liveKey.compareTo(archivedKey),
				"compareTo() must not return 0 for keys with different scopes"
			);
		}

		@Test
		@DisplayName("REFERENCED_GROUP_ENTITY_TYPE keys with different scopes should not compare as equal")
		void shouldDistinguishReferencedGroupEntityTypeKeysByScope() {
			final EntityIndexKey liveKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_GROUP_ENTITY_TYPE, Scope.LIVE, "BRAND"
			);
			final EntityIndexKey archivedKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_GROUP_ENTITY_TYPE, Scope.ARCHIVED, "BRAND"
			);

			assertNotEquals(liveKey, archivedKey);
			assertNotEquals(
				0, liveKey.compareTo(archivedKey),
				"compareTo() must not return 0 for group entity type keys with different scopes"
			);
		}

		@Test
		@DisplayName("REFERENCED_ENTITY keys with different scopes should not compare as equal")
		void shouldDistinguishReferencedEntityKeysByScope() {
			final RepresentativeReferenceKey rrk = new RepresentativeReferenceKey(
				new ReferenceKey("CATEGORY", 1)
			);
			final EntityIndexKey liveKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY, Scope.LIVE, rrk
			);
			final EntityIndexKey archivedKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY, Scope.ARCHIVED, rrk
			);

			assertNotEquals(liveKey, archivedKey);
			assertNotEquals(
				0, liveKey.compareTo(archivedKey),
				"compareTo() must not return 0 for entity keys with different scopes"
			);
		}

		@Test
		@DisplayName("REFERENCED_GROUP_ENTITY keys with different scopes should not compare as equal")
		void shouldDistinguishReferencedGroupEntityKeysByScope() {
			final RepresentativeReferenceKey rrk = new RepresentativeReferenceKey(
				new ReferenceKey("BRAND", 5)
			);
			final EntityIndexKey liveKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_GROUP_ENTITY, Scope.LIVE, rrk
			);
			final EntityIndexKey archivedKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_GROUP_ENTITY, Scope.ARCHIVED, rrk
			);

			assertNotEquals(liveKey, archivedKey);
			assertNotEquals(
				0, liveKey.compareTo(archivedKey),
				"compareTo() must not return 0 for group entity keys with different scopes"
			);
		}

		@Test
		@DisplayName("TreeSet should keep both keys when scopes differ")
		void shouldKeepBothKeysInTreeSet() {
			final EntityIndexKey liveKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.LIVE, "CATEGORY"
			);
			final EntityIndexKey archivedKey = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.ARCHIVED, "CATEGORY"
			);

			final TreeSet<EntityIndexKey> set = new TreeSet<>();
			set.add(liveKey);
			set.add(archivedKey);

			assertEquals(
				2, set.size(),
				"TreeSet must contain both keys since they have different scopes"
			);
		}

		@Test
		@DisplayName("identical keys should compare as equal")
		void shouldCompareIdenticalKeysAsEqual() {
			final EntityIndexKey key1 = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.LIVE, "CATEGORY"
			);
			final EntityIndexKey key2 = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.LIVE, "CATEGORY"
			);

			assertEquals(key1, key2);
			assertEquals(0, key1.compareTo(key2));
		}

		@Test
		@DisplayName("GLOBAL keys with different scopes should be properly ordered")
		void shouldOrderGlobalKeysByScope() {
			final EntityIndexKey liveKey = new EntityIndexKey(
				EntityIndexType.GLOBAL, Scope.LIVE
			);
			final EntityIndexKey archivedKey = new EntityIndexKey(
				EntityIndexType.GLOBAL, Scope.ARCHIVED
			);

			// GLOBAL case already handles scope -- verify it works
			assertNotEquals(liveKey, archivedKey);
			assertNotEquals(0, liveKey.compareTo(archivedKey));
		}

		@Test
		@DisplayName("compareTo should provide consistent total ordering for type + scope + discriminator")
		void shouldProvideTotalOrdering() {
			final EntityIndexKey a = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.LIVE, "A_REF"
			);
			final EntityIndexKey b = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.LIVE, "B_REF"
			);
			final EntityIndexKey aArchived = new EntityIndexKey(
				EntityIndexType.REFERENCED_ENTITY_TYPE, Scope.ARCHIVED, "A_REF"
			);

			// a < b (same scope, discriminator ordering)
			assertTrue(a.compareTo(b) < 0);
			// Scope ordering should be consistent (LIVE=0, ARCHIVED=1)
			// Either a < aArchived or a > aArchived, but not equal
			assertNotEquals(0, a.compareTo(aArchived));
		}
	}
}
