POST /rest/evita/product/query

{
  "filterBy" : {
    "referenceBrandHaving" : [
      {
        "entityHaving" : {
          "attributeCodeEquals" : "apple"
        }
      }
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceBrandContent" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      }
    }
  }
}