POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "e-readers"
      }
    },
    "userFilter" : [
      {
        "facetBrandHaving" : {
          "entityHaving" : {
            "attributeCodeInSet" : [
              "amazon"
            ]
          }
        }
      }
    ]
  },
  "require" : {
    "referenceBrandSummary" : {
      "statisticsDepth" : "IMPACT",
      "requirements" : [
        {
          "entityFetch" : {
            "attributeContent" : [
              "code"
            ]
          }
        }
      ]
    }
  }
}