POST /rest/evita/Product/query

{
  "filterBy" : {
    "referenceBrandHaving" : [
      {
        "entityHaving" : {
          "attributeCodeEquals" : "asus"
        }
      }
    ],
    "userFilter" : [
      {
        "facetCategoriesHaving" : {
          "entityHaving" : {
            "attributeCodeEquals" : "laptops"
          },
          "includingChildrenHaving" : {
            "attributeCodeContains" : "books"
          }
        }
      }
    ]
  },
  "require" : {
    "facetCategoriesSummary" : {
      "statisticsDepth" : "IMPACT",
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      }
    }
  }
}