POST /rest/evita/Product/query

{
  "filterBy" : {
    "referenceBrandHaving" : [
      {
        "entityHaving" : {
          "attributeCodeEquals" : "asus"
        }
      }
    ],
    "userFilter" : [
      {
        "facetCategoriesHaving" : {
          "entityHaving" : {
            "attributeCodeEquals" : "laptops"
          },
          "includingChildrenExcept" : {
            "attributeCodeContains" : "books"
          }
        }
      }
    ]
  },
  "require" : {
    "referenceCategoriesSummary" : {
      "statisticsDepth" : "IMPACT",
      "requirements" : [
        {
          "entityFetch" : {
            "attributeContent" : [
              "code"
            ]
          }
        }
      ]
    }
  }
}