{
  queryProduct(
    filterBy: {
      hierarchyCategoriesWithin: {
        ofParent: {
          attributeCodeEquals: "e-readers"
        }
      },
      userFilter: [
        {
          referenceParameterValuesHistogramHaving: {
            histogramName: "intervalParameterValues",
            from: 200,
            to: 400,
            groupHaving: {
              attributeCodeEquals: "weight"
            }
          }
        },
        {
          referenceParameterValuesHistogramHaving: {
            histogramName: "intervalParameterValues",
            from: 6,
            to: 10,
            groupHaving: {
              attributeCodeEquals: "thickness"
            }
          }
        }
      ]
    }
  ) {
    recordPage(size: 5) {
      data {
        primaryKey
        attributes {
          code
        }
      }
    }
    extraResults {
      referenceSummary {
        parameterValues {
          count
          groupEntity {
            primaryKey
            attributes {
              code
            }
          }
          histogramStatistics {
            intervalParameterValues {
              min
              max
              overallCount
              buckets(requestedCount: 20) {
                threshold
                occurrences
                requested
              }
            }
          }
        }
      }
    }
  }
}