POST /rest/evita/Product/query

{
  "filterBy" : {
    "referenceRelatedProductsHaving" : [ ]
  },
  "require" : {
    "entityFetch" : {
      "referenceRelatedProductsContentWithAttributes" : {
        "attributeContent" : [
          "category"
        ]
      }
    }
  }
}