POST /rest/evita/product/query

{
  "filterBy" : {
    "referenceRelatedProductsHaving" : [
      {
        "attributeCategoryEquals" : "alternativeProduct"
      }
    ]
  },
  "require" : {
    "entityFetch" : {
      "referenceRelatedProductsContentWithAttributes" : {
        "attributeContent" : [
          "category"
        ]
      }
    }
  }
}