POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeValidityInRange" : "2023-12-05T12:00:00+01:00"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ]
    }
  }
}