POST /rest/evita/Product/query

{
  "filterBy" : {
    "userFilter" : [
      {
        "facetParameterValuesHaving" : [
          {
            "entityHaving" : {
              "attributeCodeInSet" : [
                "ram-memory-24"
              ]
            }
          }
        ]
      }
    ]
  },
  "require" : {
    "facetParameterValuesSummary" : {
      "statisticsDepth" : "IMPACT",
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        },
        "entityGroupFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      },
      "filterBy" : {
        "attributeCodeContains" : "4"
      },
      "filterGroupBy" : {
        "attributeCodeInSet" : [
          "ram-memory",
          "rom-memory"
        ]
      }
    },
    "facetParameterValuesGroupsExclusivity" : {
      "filterBy" : {
        "attributeCodeInSet" : [
          "ram-memory"
        ]
      }
    }
  }
}