POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "accessories"
      }
    },
    "attributeStatusEquals" : "ACTIVE",
    "entityLocaleEquals" : "en"
  },
  "require" : {
    "facetSummary" : {
      "statisticsDepth" : "COUNTS",
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "name"
          ]
        },
        "entityGroupFetch" : {
          "attributeContent" : [
            "name"
          ]
        }
      }
    }
  }
}