POST /rest/evita/Product/query

{
  "filterBy" : {
    "userFilter" : [
      {
        "facetGroupsHaving" : {
          "entityHaving" : {
            "attributeCodeInSet" : [
              "sale"
            ]
          }
        }
      }
    ]
  },
  "require" : {
    "referenceGroupsSummary" : {
      "statisticsDepth" : "IMPACT",
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      }
    },
    "facetGroupsGroupsConjunction" : { }
  }
}