POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeStatusEquals" : "ACTIVE"
  },
  "require" : {
    "facetParameterValuesSummary" : {
      "statisticsDepth" : "COUNTS",
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        },
        "entityGroupFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      },
      "filterBy" : {
        "attributeCodeContains" : "ar"
      },
      "filterGroupBy" : {
        "attributeCodeStartsWith" : "o"
      }
    }
  }
}