POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "e-readers"
      }
    },
    "attributeStatusEquals" : "ACTIVE"
  },
  "require" : {
    "facetParameterValuesSummary" : {
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        },
        "entityGroupFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      }
    }
  }
}