POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeStatusEquals" : "ACTIVE"
  },
  "require" : {
    "facetSummary" : {
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "code"
          ]
        },
        "entityGroupFetch" : {
          "attributeContent" : [
            "code"
          ]
        }
      }
    }
  }
}