{
  queryProduct(
    filterBy: {
      userFilter: [
        {
          facetGroupsHaving: {
            entityHaving: {
              attributeCodeInSet: [
                "sale"
              ]
            }
          }
        }
      ]
    },
    require: {
      facetGroupsGroupsConjunction: { }
    }
  ) {
    extraResults {
      referenceSummary {
        groups {
          count
          facetStatistics {
            requested
            count
            impact {
              difference
              matchCount
              hasSense
            }
            facetEntity {
              primaryKey
              attributes {
                code
              }
            }
          }
        }
      }
    }
  }
}