POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "e-readers"
      }
    },
    "attributeStatusEquals" : "ACTIVE",
    "entityLocaleEquals" : "en"
  },
  "require" : {
    "facetParameterValuesSummary" : {
      "statisticsDepth" : "COUNTS",
      "requirements" : {
        "entityFetch" : {
          "attributeContent" : [
            "name"
          ]
        },
        "entityGroupFetch" : {
          "attributeContent" : [
            "name"
          ]
        }
      },
      "orderBy" : [
        {
          "attributeNameNatural" : "ASC"
        }
      ],
      "orderGroupBy" : [
        {
          "attributeNameNatural" : "ASC"
        }
      ]
    }
  }
}