{
  queryProduct(
    filterBy: {
      hierarchyCategoriesWithin: {
        ofParent: { attributeCodeEquals: "e-readers" }
      },
      entityLocaleEquals: en
    }
  ) {
    recordPage(number: 1, size: 5) {
      data {
        primaryKey
        attributes(locale: en) { code }
      }
    }
    extraResults {
      referenceSummary {
        parameterValues {
          count
          groupEntity {
            primaryKey
            attributes(locale: en) { code }
          }
          facetStatistics {
            requested
            count
            facetEntity {
              primaryKey
              attributes(locale: en) { code }
            }
          }
        }
      }
    }
  }
}
