{
  queryProduct(
    filterBy: {
      attributeStatusEquals: "ACTIVE"
    }
  ) {
    extraResults {
      referenceSummary {
        parameterValues(
          filterGroupBy: {
            attributeCodeStartsWith: "o"
          }
        ) {
          count
          groupEntity {
            primaryKey
            attributes {
              code
            }
          }
          facetStatistics(
            filterBy: {
              attributeCodeContains: "ar"
            }
          ) {
            requested
            count
            facetEntity {
              primaryKey
              attributes {
                code
              }
            }
          }
        }
      }
    }
  }
}