POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeStatusEquals" : "ACTIVE"
  },
  "require" : {
    "referenceSummary" : {
      "requirements" : [
        {
            "entityFetch" : {
              "attributeContent" : [
                "code"
              ]
            }
        },
        {
            "entityGroupFetch" : {
              "attributeContent" : [
                "code"
              ]
            }
        }
      ]
    }
  }
}