POST /rest/evita/Product/list

{
  "filterBy": {
    "priceInPriceLists": ["basic"],
    "priceInCurrency": "EUR",
    "priceBetween": ["300", null],
    "entityLocaleEquals": "en"
  },
  "orderBy": [{
    "priceNatural": "ASC"
  }],
  "require": {
    "entityFetch": {
      "attributeContentAll": true,
      "associatedDataContentAll": true,
      "priceContentAll": true,
      "referenceContentAllWithAttributes": {},
      "dataInLocales": []
    }
  }
}