POST /rest/evita/Brand/list

{
  "filterBy": {
    "attributeNameStartsWith": "A"
  },
  "orderBy": [{
    "attributeNameNatural": "ASC"
  }],
  "require": {
    "entityFetch": {
      "attributeContentAll": true,
      "associatedDataContentAll": true,
      "referenceContentAllWithAttributes": {},
      "dataInLocales": []
    }
  }
}