POST /rest/evita/Product/list

{
  "filterBy": {
    "entityLocaleEquals": "en"
  },
  "require": {
    "entityFetch": {
      "attributeContentAll": true,
      "associatedDataContentAll": true,
      "priceContentAll": true,
      "referenceContentAllWithAttributes": {},
      "dataInLocales": []
    }
  }
}