POST /rest/evita/Brand/query

{
  "filterBy" : {
    "and" : [
      {
        "attributeNameStartsWith" : "A",
        "entityLocaleEquals" : "en"
      }
    ]
  },
  "orderBy" : [
    {
      "attributeNameNatural" : "ASC"
    }
  ],
  "require" : {
    "entityFetch" : { }
  }
}