POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeUrlEquals" : "/en/macbook-pro-13-2022",
    "entityLocaleEquals" : "en"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "name"
      ],
      "referenceCategoriesContent" : {
        "entityFetch" : {
          "attributeContent" : [
            "code",
            "name"
          ],
          "hierarchyContent" : {
            "entityFetch" : {
              "attributeContent" : [
                "code",
                "name",
                "level"
              ]
            }
          }
        }
      }
    }
  }
}