POST /rest/evita/Product/query

{
  "filterBy" : {
    "entityLocaleEquals" : "en",
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeUrlEquals" : "/en/smartwatches"
      }
    },
    "priceInPriceLists" : [
      "basic"
    ],
    "priceInCurrency" : "EUR",
    "priceValidInNow" : true,
    "userFilter" : [
      {
        "priceBetween" : [
          "50",
          "400"
        ]
      }
    ]
  },
  "require" : {
    "priceHistogram" : {
      "requestedBucketCount" : 10
    }
  }
}