{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "vouchers-for-shareholders"
      }
    },
    "entityLocaleEquals" : "cs-CZ"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "name"
      ]
    }
  }
}