POST /rest/evita/category/query

{
  "filterBy" : {
    "hierarchyWithinSelf" : {
      "ofParent" : {
        "attributeCodeStartsWith" : "wire"
      }
    }
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ]
    }
  }
}