POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeProductTypeInSet" : [
      "BASIC",
      "MASTER"
    ],
    "hierarchyCategoriesWithinRoot" : {
      "having" : [
        {
          "attributeStatusEquals" : "ACTIVE"
        }
      ],
      "anyHaving" : [
        {
          "and" : [
            {
              "referenceTagsHaving" : [
                {
                  "entityHaving" : {
                    "attributeCodeEquals" : "HP"
                  }
                }
              ],
              "referenceProductsHaving" : [
                {
                  "entityHaving" : {
                    "attributeStatusEquals" : "ACTIVE"
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "require" : {
    "page" : {
      "number" : 1,
      "size" : 10
    },
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ]
    }
  }
}