POST /rest/evita/product/query

{
  "filterBy" : {
    "attributeBatteryLifeGreaterThan" : "40"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "battery-life"
      ]
    }
  }
}