POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeCodeEquals" : "apple-iphone-13-pro-3"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ]
    }
  }
}