POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeBatteryCapacityBetween" : [
      "125",
      "160"
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "battery-capacity"
      ]
    }
  }
}