POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeBatteryCapacityLessThanEquals" : "125"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "battery-capacity"
      ]
    }
  }
}