POST /rest/evita/Product/query

{
  "filterBy" : {
    "attributeCatalogNumberIs" : "NOT_NULL"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "catalogNumber"
      ]
    }
  }
}