POST /rest/evita/product/query

{
  "orderBy" : {
    "attributeOrderedQuantityNatural" : "DESC"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "orderedQuantity"
      ]
    }
  }
}