POST /rest/evita/product/query

{
  "orderBy" : [
    {
      "attributeEanNatural" : "ASC"
    },
    {
      "attributeCatalogNumberNatural" : "DESC"
    }
  ],
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code",
        "ean",
        "catalogNumber"
      ]
    }
  }
}