POST /rest/evita/product/query

{
  "filterBy" : {
    "entityLocaleEquals" : "cs"
  },
  "orderBy" : [
    {
      "attributeNameNatural" : "ASC"
    }
  ],
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "name"
      ]
    }
  }
}