POST /rest/evita/Product/query

{
  "filterBy" : {
    "priceInPriceLists" : [
      "b2b-basic-price"
    ],
    "priceInCurrency" : "EUR"
  },
  "orderBy" : [
    {
      "priceDiscount" : {
        "inPriceLists" : [
          "basic"
        ]
      }
    }
  ],
  "require" : {
    "entityFetch" : {
      "priceContentRespectingFilter" : [
        "basic"
      ]
    }
  }
}