POST /rest/evita/Product/query

{
  "filterBy" : {
    "priceInPriceLists" : [
      "basic"
    ],
    "priceInCurrency" : "EUR"
  },
  "orderBy" : [
    {
      "priceNatural" : "DESC"
    }
  ],
  "require" : {
    "entityFetch" : {
      "priceContentRespectingFilter" : [ ]
    }
  }
}