POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "e-readers"
      }
    },
    "priceInPriceLists" : [
      "basic"
    ],
    "priceInCurrency" : "EUR",
    "userFilter" : [
      {
        "priceBetween" : [
          "150.0",
          "170.5"
        ]
      }
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "priceContentRespectingFilter" : [ ]
    }
  }
}