POST /rest/evita/Product/query

{
  "filterBy" : {
    "priceInCurrency" : "EUR"
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "priceContentRespectingFilter" : [ ]
    }
  }
}