POST /rest/evita/Product/query

{
  "filterBy" : {
    "priceInPriceLists" : [
      "basic"
    ],
    "priceInCurrency" : "EUR",
    "priceValidInNow" : true
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "priceContentRespectingFilter" : [ ]
    }
  }
}