/*
 *
 *                         _ _        ____  ____
 *               _____   _(_) |_ __ _|  _ \| __ )
 *              / _ \ \ / / | __/ _` | | | |  _ \
 *             |  __/\ V /| | || (_| | |_| | |_) |
 *              \___| \_/ |_|\__\__,_|____/|____/
 *
 *   Copyright (c) 2024-2026
 *
 *   Licensed under the Business Source License, Version 1.1 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   https://github.com/FgForrest/evitaDB/blob/master/LICENSE
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package io.evitadb.externalApi.observability.agent;

import java.util.function.Consumer;

/**
 * Mediator between the advice woven in by `ErrorMonitoringAgent` and the observability manager, which registers the
 * lambdas to be called when an error is constructed.
 *
 * ## This class is injected into the bootstrap classloader
 *
 * `ErrorMonitoringAgent#premain` injects these bytes into the bootstrap loader, so that the advice - which ends up
 * inlined into exception constructors loaded by every classloader in the JVM - can always resolve it. A bootstrap
 * class can only see `java.*`. **No signature or method body here may name a type from `io.evitadb`, from Lombok's
 * runtime, or from any library**: doing so compiles, passes every unit test, and then fails with
 * `NoClassDefFoundError` only in an agent-attached server. That is why the parameters below are
 * `java.lang.Throwable` and `java.util.function.Consumer`, why nothing is annotated, and why the types this class
 * talks about are named in prose rather than linked - a javadoc `{@link}` would need an import, and an import here
 * is one careless "optimise imports" away from becoming a real reference.
 *
 * Everything that needs to inspect the exception - reading its type, honouring the `io.evitadb.exception.NotMonitored`
 * opt-out, resolving where it was created - therefore happens on the consumer side, in the observability manager,
 * which is an ordinary application class.
 *
 * @author Jan Novotný (novotny@fg.cz), FG Forrest a.s. (c) 2024
 */
public class ErrorMonitor {
	private static Consumer<Throwable> javaErrorConsumer;
	private static Consumer<Throwable> evitaErrorConsumer;
	private static Consumer<Throwable> clientErrorConsumer;

	/**
	 * Marks the thread as being inside a consumer, so an error constructed anywhere below one - by a metrics
	 * library, by annotation parsing, by the logging framework - is dropped instead of re-entering here and
	 * recursing until the stack is exhausted.
	 *
	 * This is the right level for the guard: everything a consumer does runs beneath these three methods, whereas a
	 * guard further in protects only the part of the consumer that comes after it.
	 */
	private static final ThreadLocal<Boolean> REPORTING = new ThreadLocal<>();

	/**
	 * Registers the consumer notified when a JVM error is constructed.
	 *
	 * Written by hand rather than generated by Lombok: a generated member carries a `lombok.Generated` annotation,
	 * and a bootstrap class has no business naming a third-party type at all - even one whose retention happens to
	 * keep it from being resolved today.
	 *
	 * @param consumer consumer to notify, or null to stop reporting
	 */
	public static void setJavaErrorConsumer(Consumer<Throwable> consumer) {
		javaErrorConsumer = consumer;
	}

	/**
	 * Registers the consumer notified when an evitaDB internal error is constructed - see
	 * {@link #setJavaErrorConsumer} for why this is not generated.
	 *
	 * @param consumer consumer to notify, or null to stop reporting
	 */
	public static void setEvitaErrorConsumer(Consumer<Throwable> consumer) {
		evitaErrorConsumer = consumer;
	}

	/**
	 * Registers the consumer notified when an evitaDB client error is constructed - see
	 * {@link #setJavaErrorConsumer} for why this is not generated.
	 *
	 * @param consumer consumer to notify, or null to stop reporting
	 */
	public static void setClientErrorConsumer(Consumer<Throwable> consumer) {
		clientErrorConsumer = consumer;
	}

	/**
	 * Called by the agent advice when a JVM error (a `java.lang.VirtualMachineError`) is constructed.
	 *
	 * @param error the error being constructed; not yet fully initialised
	 */
	public static void registerJavaError(Throwable error) {
		dispatch(javaErrorConsumer, error);
	}

	/**
	 * Called by the agent advice when an evitaDB internal error (an `io.evitadb.exception.EvitaInternalError`) is
	 * constructed.
	 *
	 * @param error the error being constructed; not yet fully initialised
	 */
	public static void registerEvitaError(Throwable error) {
		dispatch(evitaErrorConsumer, error);
	}

	/**
	 * Called by the agent advice when a client error (an `io.evitadb.exception.EvitaInvalidUsageException`) is
	 * constructed.
	 *
	 * @param error the error being constructed; not yet fully initialised
	 */
	public static void registerClientError(Throwable error) {
		dispatch(clientErrorConsumer, error);
	}

	/**
	 * Hands the error to a consumer, guarding the two things that make this position dangerous: it runs inside an
	 * exception constructor, on a partially constructed object, woven in by the agent.
	 *
	 * Nothing may escape - a throwable leaving here would surface from `new SomeException(...)` at a call site with
	 * no way to handle it - and nothing may re-enter, because an error constructed inside a consumer would be
	 * reported, re-entering, until the stack runs out. Losing a metric increment is the only acceptable outcome.
	 *
	 * @param consumer consumer to notify, may be null when nothing has registered yet
	 * @param error    the error being constructed
	 */
	private static void dispatch(Consumer<Throwable> consumer, Throwable error) {
		if (consumer == null || Boolean.TRUE.equals(REPORTING.get())) {
			return;
		}
		REPORTING.set(Boolean.TRUE);
		try {
			consumer.accept(error);
		} catch (Throwable ignored) {
			// deliberately swallowed - see the method comment; there is no caller that could act on this
		} finally {
			REPORTING.set(Boolean.FALSE);
		}
	}

}
