POST /rest/evita/Product/query

{
  "require" : {
    "attributeHistogram" : {
      "requestedBucketCount" : 20,
      "behavior" : "STANDARD",
      "attributeNames" : [
        "width",
        "height"
      ]
    }
  }
}