/*
 *
 *                         _ _        ____  ____
 *               _____   _(_) |_ __ _|  _ \| __ )
 *              / _ \ \ / / | __/ _` | | | |  _ \
 *             |  __/\ V /| | || (_| | |_| | |_) |
 *              \___| \_/ |_|\__\__,_|____/|____/
 *
 *   Copyright (c) 2026
 *
 *   Licensed under the Business Source License, Version 1.1 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   https://github.com/FgForrest/evitaDB/blob/master/LICENSE
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package io.evitadb.index.fulltext.analysis;

import javax.annotation.Nonnull;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * **Prototype, test scope only.** The Snowball Romanian stemmer that Lucene 9.12.3 ships
 * (`org.tartarus.snowball.ext.RomanianStemmer`, generated by Snowball 2.0) with its tables rewritten into
 * **diacritics-folded space**, so the stemmer can run **after** folding instead of before it — mechanism M1 of
 * the prior-art survey, and the query half of mechanism M7, applied to Romanian
 * (`documentation/adr/2026-08-24-fulltext-search-lucene-vs-inhouse/prototypes/p5-prior-art-sk-pl-ro.md`, §4).
 *
 * **The port is almost entirely mechanical, because Romanian folding never turns a vowel into a consonant.**
 * `ă`/`â` fold to `a` and `î` folds to `i` — all vowels before and after — so the region marking (`RV`, `R1`,
 * `R2`) that gates every rule is **identical** on folded and accented input, something that had to be verified
 * rather than assumed (the survey §4 suspected region drift; there is none). The `ş`→`s`, `ţ`→`t` foldings
 * collapse many table entries onto plain-letter ones, and wherever the collision partner carries the same
 * action (`ată`→`ata` onto `ata`, `işti`→`isti` onto `isti`, `icităţi`→`icitati` onto `icitati`, …) the
 * collapse is harmless and done unconditionally here.
 *
 * Note this ports the **Snowball 2.0** tables — the ones actually shipped in the pinned Lucene — which are
 * written in the **cedilla** orthography (`ş` U+015F, `ţ` U+0163) and contain no comma-below (`ș`/`ț`) entries
 * at all. In folded space that distinction disappears, which is exactly why this port also repairs the
 * cedilla-vs-comma encoding split that breaks the accented stemmer (see the fixture's encoding probes).
 *
 * **Three rules cannot be folded mechanically, and each is a genuine language judgment.** All three are
 * switchable, so the cost of each switch position can be measured rather than argued:
 *
 * - **{@link #tiuneRewrite}** — the original rewrites `ţiune`/`ţiuni` to `t` (`gravitaţiune` → `gravitat`) by
 *   matching a literal `ţ` before the `iune`. Folded, `ţ` is indistinguishable from `t`, so the rule also
 *   fires on the rare genuine `-tiune` words (`chestiune` → `chest` instead of the accented chain's
 *   `chestiun`).
 * - **{@link #sVerbEndings}** — the verb table's endings spelled with `ş` (`eşte`, `eşti`, `aşi`, `işi`, …)
 *   fold onto plain-`s` strings that genuinely occur word-finally in nouns: with the entries included, folded
 *   `veste` (from *vestă*, a garment) loses `este` as if it were the verb ending of *a vesti*.
 * - **{@link #amUnconditional}** — the verb table holds `am` with the *conditional* delete (only after a
 *   consonant or `u`) and `âm`/`ăm` with the *unconditional* one. Folded, all three are `am`, and the two
 *   actions genuinely differ; the switch selects which of the two behaviours folded `am` gets.
 * - **{@link #aVerbEndings}** — the verb endings spelled with `ă`/`â` and **no plain-spelling partner** in the
 *   original table (`ară`, `ăsc`, `ând`, `ească`, `ează`, the `arăm`/`serăm` family, …) fold onto plain-letter
 *   strings that genuine words end with: folded `cumpara` (infinitive *cumpăra*) matches folded `ară` and loses
 *   three letters where the accented chain strips only the final vowel. **This ambiguity was not predicted by
 *   the survey** — it was found by the first M7 measurement run, the same way the Czech epenthetic-`e`
 *   ambiguity was: a symmetric folded chain mis-stems both sides identically and still converges, so only the
 *   asymmetric mechanism can see it. (Entries whose plain partner exists with the same action — `âre`/`are`,
 *   `âse`/`ase` — are kept unconditionally: the accented chain fires on the plain spelling too.)
 *
 * **NOTE**: input is expected to be lowercased **and diacritics-folded** — the exact opposite of the Snowball
 * stemmer's contract. Fed accented text it silently stops recognising most endings, the same failure mode in
 * mirror image.
 *
 * @author Lukáš Hornych (hornych@fg.cz), FG Forrest a.s. (c) 2026
 */
final class FoldedRomanianStemmer implements FoldedStemmer {

	/**
	 * One suffix entry of a table: the folded suffix text and the action code of the original Snowball rule.
	 *
	 * @param suffix folded suffix, matched at the end of the current buffer
	 * @param action action code, interpreted by the step that owns the table
	 */
	private record Ending(@Nonnull String suffix, int action) {
	}

	/**
	 * Step 0 endings (the Snowball `a_1`, plural/article removal, gated on R1). Actions: 1 delete, 2 → `a`,
	 * 3 → `e`, 4 → `i`, 5 → `i` unless preceded by `ab`, 6 → `at`, 7 → `ati` (the folded image of the
	 * original's → `aţi`).
	 */
	private static final List<Ending> STEP0_ENDINGS = byLengthDescending(
		new Ending("ea", 3), new Ending("atia", 7), new Ending("aua", 2), new Ending("iua", 4),
		new Ending("atie", 7), new Ending("ele", 3), new Ending("ile", 5), new Ending("iile", 4),
		new Ending("iei", 4), new Ending("atei", 6), new Ending("ii", 4), new Ending("ului", 1),
		new Ending("ul", 1), new Ending("elor", 3), new Ending("ilor", 4), new Ending("iilor", 4)
	);

	/**
	 * Combo-suffix endings (the Snowball `a_2`, derivational chains, gated on R1 and applied repeatedly).
	 * Actions: 1 → `abil`, 2 → `ibil`, 3 → `iv`, 4 → `ic`, 5 → `at`, 6 → `it`. Folded duplicates
	 * (`ătoare`/`atoare`, `icităţi`/`icitati`, the `-ă` feminines, …) are collapsed — every collision partner
	 * carried the same action.
	 */
	private static final List<Ending> COMBO_ENDINGS = byLengthDescending(
		new Ending("icala", 4), new Ending("iciva", 4), new Ending("ativa", 5), new Ending("itiva", 6),
		new Ending("icale", 4), new Ending("atiune", 5), new Ending("itiune", 6), new Ending("atoare", 5),
		new Ending("itoare", 6), new Ending("icitate", 4), new Ending("abilitate", 1),
		new Ending("ibilitate", 2), new Ending("ivitate", 3), new Ending("icive", 4), new Ending("ative", 5),
		new Ending("itive", 6), new Ending("icali", 4), new Ending("atori", 5), new Ending("icatori", 4),
		new Ending("itori", 6), new Ending("icitati", 4), new Ending("abilitati", 1), new Ending("ivitati", 3),
		new Ending("icivi", 4), new Ending("ativi", 5), new Ending("itivi", 6), new Ending("icitai", 4),
		new Ending("abilitai", 1), new Ending("ivitai", 3), new Ending("ical", 4), new Ending("ator", 5),
		new Ending("icator", 4), new Ending("itor", 6), new Ending("iciv", 4), new Ending("ativ", 5),
		new Ending("itiv", 6)
	);

	/**
	 * Standard-suffix endings (the Snowball `a_3`, gated on R2). Actions: 1 delete, 2 the `ţ`→`t` rewrite of
	 * `iune`/`iuni` (see {@link #tiuneRewrite}), 3 → `ist`. Folded duplicates collapsed as in
	 * {@link #COMBO_ENDINGS}.
	 */
	private static final List<Ending> STANDARD_ENDINGS = byLengthDescending(
		new Ending("ica", 1), new Ending("abila", 1), new Ending("ibila", 1), new Ending("oasa", 1),
		new Ending("ata", 1), new Ending("ita", 1), new Ending("anta", 1), new Ending("ista", 3),
		new Ending("uta", 1), new Ending("iva", 1), new Ending("ic", 1), new Ending("ice", 1),
		new Ending("abile", 1), new Ending("ibile", 1), new Ending("isme", 3), new Ending("iune", 2),
		new Ending("oase", 1), new Ending("ate", 1), new Ending("itate", 1), new Ending("ite", 1),
		new Ending("ante", 1), new Ending("iste", 3), new Ending("ute", 1), new Ending("ive", 1),
		new Ending("ici", 1), new Ending("abili", 1), new Ending("ibili", 1), new Ending("iuni", 2),
		new Ending("atori", 1), new Ending("osi", 1), new Ending("ati", 1), new Ending("itati", 1),
		new Ending("iti", 1), new Ending("anti", 1), new Ending("isti", 3), new Ending("uti", 1),
		new Ending("ivi", 1), new Ending("itai", 1), new Ending("abil", 1), new Ending("ibil", 1),
		new Ending("ism", 3), new Ending("ator", 1), new Ending("os", 1), new Ending("at", 1),
		new Ending("it", 1), new Ending("ant", 1), new Ending("ist", 3), new Ending("ut", 1),
		new Ending("iv", 1)
	);

	/**
	 * Vowel-suffix endings (the Snowball `a_5`, gated on RV): delete. `ă` folds onto the existing `a` entry.
	 */
	private static final List<Ending> VOWEL_ENDINGS = byLengthDescending(
		new Ending("ie", 1), new Ending("a", 1), new Ending("e", 1), new Ending("i", 1)
	);

	/**
	 * Whether the `ţiune`/`ţiuni` → `t` rewrite of the standard-suffix step is applied to folded `tiune`/
	 * `tiuni`. See the class javadoc — it buys the `-ţiune` abstract nouns (their folded image matches the
	 * accented chain's output) and costs the rare genuine `-tiune` words a divergent, shorter stem.
	 */
	private final boolean tiuneRewrite;
	/**
	 * Whether the verb endings spelled with `ş` in the original table are included in their folded spelling.
	 * See the class javadoc — they buy the `-eşte`/`-eşti` verb forms and cost every noun genuinely ending in
	 * the same plain-`s` strings.
	 */
	private final boolean sVerbEndings;
	/**
	 * Whether folded `am` gets the unconditional delete of the original's `âm`/`ăm` entries rather than the
	 * conditional delete of the original's `am` entry. See the class javadoc.
	 */
	private final boolean amUnconditional;
	/**
	 * Whether the verb endings spelled with `ă`/`â` in the original table — the ones without a plain-spelling
	 * partner — are included in their folded spelling. See the class javadoc; found by the first M7 run.
	 */
	private final boolean aVerbEndings;
	/**
	 * Whether the combo pre-pass (`a_2`) runs. Split from the `a_3` gate by the sweep's third round: after a
	 * combo rewrite the folded `a_3` can over-delete where the accented `a_3` deleted differently
	 * (`descălicător` → combo `icator`→`ic`, then folded `a_3` eats the `ic` the accented side kept), so
	 * combo-on-with-`a_3`-off is a hypothesis of its own.
	 */
	private final boolean comboStep;
	/**
	 * Whether the standard-suffix table (`a_3`) runs. The ro_RO lexicon sweep showed whole folded `a_3` entries
	 * (`ita`, `ata`, `at`) collide with `ţ`-stem words plus a genuine vowel ending (`bogdăniţa` → accented
	 * strips only `a`, folded `ita` eats three letters), and the accented behaviour there is "vowel strip only"
	 * — reachable exactly by a hypothesis with this step off.
	 */
	private final boolean a3Step;
	/**
	 * Whether the verb-suffix step runs at all. The same sweep showed plain verb entries (`sei`, `use`, `ai`,
	 * `au`) collide with `ş`/`ă`-stem words plus a genuine vowel ending (`borşei` → accented strips only `i`),
	 * and the accented behaviour is again "vowel strip only" — reachable by a hypothesis with this step off.
	 */
	private final boolean verbStep;
	/**
	 * Whether the plural/article step (`a_1`) runs at all. The ro_RO sweep's second round showed folded `a_1`
	 * entries collide with `ţ`-stem words plus the vowel the accented chain strips (`frecăţei` → accented
	 * strips only `i`, folded `atei` → `at` eats four letters).
	 */
	private final boolean step0Step;
	/**
	 * Whether the final-vowel step (`a_5`) runs at all. The accented `a_5` holds `a`/`e`/`ie`/`i`/`ă` but not
	 * `â`, so folded final `a` over-strips words the accented chain leaves vowel-final (`pârâul` → accented
	 * `pârâ`, folded strips the `a` too).
	 */
	private final boolean vowelStep;
	/**
	 * The verb-suffix table (the Snowball `a_4`, matched inside RV), assembled per instance because its
	 * content depends on {@link #sVerbEndings}, {@link #amUnconditional} and {@link #aVerbEndings}. Actions:
	 * 1 delete when preceded
	 * (inside RV) by a non-vowel or by `u`, 2 delete unconditionally.
	 */
	@Nonnull private final List<Ending> verbEndings;

	/**
	 * Creates a stemmer with the first three fold-ambiguous rules independently enabled or disabled and the
	 * `ă`-spelled verb endings kept enabled, which is the fold-faithful behaviour every symmetric chain wants.
	 *
	 * @param tiuneRewrite    whether folded `tiune`/`tiuni` is rewritten to `t`
	 * @param sVerbEndings    whether the folded images of the `ş`-spelled verb endings are stripped
	 * @param amUnconditional whether folded `am` is deleted unconditionally
	 */
	FoldedRomanianStemmer(boolean tiuneRewrite, boolean sVerbEndings, boolean amUnconditional) {
		this(tiuneRewrite, sVerbEndings, amUnconditional, true);
	}

	/**
	 * Creates a stemmer with all four fold-ambiguous rules independently enabled or disabled.
	 *
	 * @param tiuneRewrite    whether folded `tiune`/`tiuni` is rewritten to `t`
	 * @param sVerbEndings    whether the folded images of the `ş`-spelled verb endings are stripped
	 * @param amUnconditional whether folded `am` is deleted unconditionally
	 * @param aVerbEndings    whether the folded images of the partnerless `ă`/`â`-spelled verb endings are
	 *                        stripped
	 */
	FoldedRomanianStemmer(
		boolean tiuneRewrite,
		boolean sVerbEndings,
		boolean amUnconditional,
		boolean aVerbEndings
	) {
		this(tiuneRewrite, sVerbEndings, amUnconditional, aVerbEndings, true, true);
	}

	/**
	 * Creates a stemmer with all four fold-ambiguous rules independently enabled or disabled, and the two
	 * whole-step gates the lexicon sweep introduced (see {@link #standardStep} and {@link #verbStep}).
	 *
	 * @param tiuneRewrite    whether folded `tiune`/`tiuni` is rewritten to `t`
	 * @param sVerbEndings    whether the folded images of the `ş`-spelled verb endings are stripped
	 * @param amUnconditional whether folded `am` is deleted unconditionally
	 * @param aVerbEndings    whether the folded images of the partnerless `ă`/`â`-spelled verb endings are
	 *                        stripped
	 * @param standardStep    whether the combo and standard-suffix steps run
	 * @param verbStep        whether the verb-suffix step runs
	 */
	FoldedRomanianStemmer(
		boolean tiuneRewrite,
		boolean sVerbEndings,
		boolean amUnconditional,
		boolean aVerbEndings,
		boolean standardStep,
		boolean verbStep
	) {
		this(
			tiuneRewrite, sVerbEndings, amUnconditional, aVerbEndings, standardStep, standardStep, verbStep,
			true, true
		);
	}

	/**
	 * Creates a stemmer with the four fold-ambiguous rules and all four pipeline-step gates. The gates exist
	 * because the accented stemmer's path through the pipeline is itself part of what folding obscures — see
	 * each gate's javadoc.
	 *
	 * @param tiuneRewrite    whether folded `tiune`/`tiuni` is rewritten to `t`
	 * @param sVerbEndings    whether the folded images of the `ş`-spelled verb endings are stripped
	 * @param amUnconditional whether folded `am` is deleted unconditionally
	 * @param aVerbEndings    whether the folded images of the partnerless `ă`/`â`-spelled verb endings are
	 *                        stripped
	 * @param comboStep       whether the combo pre-pass runs
	 * @param a3Step          whether the standard-suffix table runs
	 * @param verbStep        whether the verb-suffix step runs
	 * @param step0Step       whether the plural/article step runs
	 * @param vowelStep       whether the final-vowel step runs
	 */
	FoldedRomanianStemmer(
		boolean tiuneRewrite,
		boolean sVerbEndings,
		boolean amUnconditional,
		boolean aVerbEndings,
		boolean comboStep,
		boolean a3Step,
		boolean verbStep,
		boolean step0Step,
		boolean vowelStep
	) {
		this.tiuneRewrite = tiuneRewrite;
		this.sVerbEndings = sVerbEndings;
		this.amUnconditional = amUnconditional;
		this.aVerbEndings = aVerbEndings;
		this.comboStep = comboStep;
		this.a3Step = a3Step;
		this.verbStep = verbStep;
		this.step0Step = step0Step;
		this.vowelStep = vowelStep;

		final List<Ending> endings = new ArrayList<>(96);
		// the always-present entries: spelled without diacritics in the original, or folded from ă/â/î with a
		// collision partner of the same action (âre→are, âse→ase, âi→ai, ârăţi→arăţi, …)
		endings.add(new Ending("ea", 1));
		endings.add(new Ending("ia", 1));
		endings.add(new Ending("esc", 1));
		endings.add(new Ending("ind", 1));
		endings.add(new Ending("are", 1));      // are + âre
		endings.add(new Ending("ere", 1));
		endings.add(new Ending("ire", 1));
		endings.add(new Ending("se", 2));
		endings.add(new Ending("ase", 1));      // ase + âse
		endings.add(new Ending("sese", 2));
		endings.add(new Ending("ise", 1));
		endings.add(new Ending("use", 1));
		endings.add(new Ending("eze", 1));
		endings.add(new Ending("ai", 1));       // ai + âi
		endings.add(new Ending("eai", 1));
		endings.add(new Ending("iai", 1));
		endings.add(new Ending("sei", 2));
		endings.add(new Ending("ui", 1));
		endings.add(new Ending("ezi", 1));
		endings.add(new Ending("eati", 1));     // eaţi
		endings.add(new Ending("iati", 1));     // iaţi
		endings.add(new Ending("eti", 2));      // eţi
		endings.add(new Ending("iti", 2));      // iţi
		endings.add(new Ending("serati", 2));   // serăţi
		endings.add(new Ending("aserati", 1));  // aserăţi + âserăţi
		endings.add(new Ending("seserati", 2)); // seserăţi
		endings.add(new Ending("iserati", 1));  // iserăţi
		endings.add(new Ending("userati", 1));  // userăţi
		endings.add(new Ending("irati", 1));    // irăţi
		endings.add(new Ending("urati", 1));    // urăţi
		endings.add(new Ending("em", 2));
		endings.add(new Ending("asem", 1));     // asem + âsem
		endings.add(new Ending("sesem", 2));
		endings.add(new Ending("isem", 1));
		endings.add(new Ending("usem", 1));
		endings.add(new Ending("im", 2));
		endings.add(new Ending("au", 1));
		endings.add(new Ending("eau", 1));
		endings.add(new Ending("iau", 1));
		endings.add(new Ending("indu", 1));
		endings.add(new Ending("ez", 1));
		// the folded am carries whichever action the switch selects - see the class javadoc
		endings.add(new Ending("am", amUnconditional ? 2 : 1));
		if (this.aVerbEndings) {
			endings.add(new Ending("asc", 1));      // ăsc
			endings.add(new Ending("and", 1));      // ând
			endings.add(new Ending("andu", 1));     // ându
			endings.add(new Ending("easca", 1));    // ească
			endings.add(new Ending("eaza", 1));     // ează
			endings.add(new Ending("ara", 1));      // ară + âră
			endings.add(new Ending("sera", 2));     // seră
			endings.add(new Ending("asera", 1));    // aseră + âseră
			endings.add(new Ending("sesera", 2));   // seseră
			endings.add(new Ending("isera", 1));    // iseră
			endings.add(new Ending("usera", 1));    // useră
			endings.add(new Ending("ira", 1));      // iră
			endings.add(new Ending("ura", 1));      // ură
			endings.add(new Ending("ati", 2));      // aţi + âţi - folded `ati` also arises from `ăţi` (calităţi)
			endings.add(new Ending("arati", 1));    // arăţi + ârăţi
			endings.add(new Ending("aram", 1));     // arăm + ârăm
			endings.add(new Ending("seram", 2));    // serăm
			endings.add(new Ending("aseram", 1));   // aserăm + âserăm
			endings.add(new Ending("seseram", 2));  // seserăm
			endings.add(new Ending("iseram", 1));   // iserăm
			endings.add(new Ending("useram", 1));   // userăm
			endings.add(new Ending("iram", 1));     // irăm
			endings.add(new Ending("uram", 1));     // urăm
		}
		if (sVerbEndings) {
			endings.add(new Ending("este", 1));     // eşte
			endings.add(new Ending("aste", 1));     // ăşte
			endings.add(new Ending("esti", 1));     // eşti
			endings.add(new Ending("asti", 1));     // ăşti
			endings.add(new Ending("asi", 1));      // aşi + âşi
			endings.add(new Ending("isi", 1));      // işi
			endings.add(new Ending("usi", 1));      // uşi
			endings.add(new Ending("sesi", 2));     // seşi
			endings.add(new Ending("asesi", 1));    // aseşi + âseşi
			endings.add(new Ending("sesesi", 2));   // seseşi
			endings.add(new Ending("isesi", 1));    // iseşi
			endings.add(new Ending("usesi", 1));    // useşi
		}
		this.verbEndings = byLengthDescending(endings.toArray(Ending[]::new));
	}

	/**
	 * Builds the full M7 hypothesis set: every combination of the four rule switches and the four step gates,
	 * plus the folded surface itself (the accented stemmer is inert on whole loanword classes — `-ău`, `-ăţ`
	 * toponyms — where the folded tables fire). One list shared by the R20n matrix chain and the ro_RO lexicon
	 * sweep, so the two always verify the same set. 256 configurations sounds like a fan-out — it is not: the
	 * fan-out that matters is distinct **stems per token**, measured by the matrix probe.
	 *
	 * @return every hypothesis stemmer, surface hypothesis last
	 */
	@Nonnull
	static List<FoldedStemmer> allHypotheses() {
		final List<FoldedStemmer> hypotheses = new ArrayList<>(513);
		for (int mask = 0; mask < 512; mask++) {
			hypotheses.add(new FoldedRomanianStemmer(
				(mask & 1) != 0, (mask & 2) != 0, (mask & 4) != 0, (mask & 8) != 0,
				(mask & 16) != 0, (mask & 32) != 0, (mask & 64) != 0, (mask & 128) != 0,
				(mask & 256) != 0
			));
		}
		hypotheses.add((buffer, length) -> length);
		return hypotheses;
	}

	/**
	 * Sorts table entries longest-suffix-first, which together with first-match-wins scanning reproduces the
	 * longest-match semantics of Snowball's `find_among_b`.
	 *
	 * @param endings table entries in any order
	 * @return the entries sorted by suffix length, longest first
	 */
	@Nonnull
	private static List<Ending> byLengthDescending(@Nonnull Ending... endings) {
		final List<Ending> sorted = new ArrayList<>(List.of(endings));
		sorted.sort(Comparator.comparingInt((Ending ending) -> ending.suffix().length()).reversed());
		return List.copyOf(sorted);
	}

	/**
	 * Stems an input buffer of diacritics-folded, lowercased Romanian text. Mirrors the Snowball driver:
	 * prelude (intervocalic `i`/`u` markers), region marking, step 0, standard suffixes (with the combo
	 * pre-pass), verb suffixes only when no standard suffix was removed, final vowel, postlude.
	 *
	 * @param s   input buffer
	 * @param len length of the input buffer
	 * @return length of the buffer after stemming
	 */
	@Override
	public int stem(@Nonnull char[] s, int len) {
		markIntervocalic(s, len);
		// regions are positions into the buffer; every edit below happens at the tail, so they stay valid
		final int pV = markRV(s, len);
		final int p1 = markAfterVowelConsonant(s, len, 0);
		final int p2 = markAfterVowelConsonant(s, len, p1);

		if (this.step0Step) {
			len = step0(s, len, p1);
		}
		// the combo pre-pass repeats until no entry fires; it counts as a standard-suffix removal by itself
		boolean standardRemoved = false;
		if (this.comboStep) {
			while (true) {
				final int reduced = comboSuffix(s, len, p1);
				if (reduced == len) {
					break;
				}
				standardRemoved = true;
				len = reduced;
			}
		}
		if (this.a3Step) {
			// the a_3 pass can fire without changing the length (`ist` -> `ist`) and still counts as a
			// removal - hence the sentinel rather than a length comparison
			final int afterStandard = standardSuffix(s, len, p2);
			if (afterStandard >= 0) {
				standardRemoved = true;
				len = afterStandard;
			}
		}
		if (!standardRemoved && this.verbStep) {
			len = verbSuffix(s, len, pV);
		}
		if (this.vowelStep) {
			len = vowelSuffix(s, len, pV);
		}
		unmarkIntervocalic(s, len);
		return len;
	}

	/**
	 * Marks intervocalic `i` and `u` with their uppercase counterparts so the tables treat them as consonants,
	 * exactly as the Snowball prelude does. The markers are reverted by {@link #unmarkIntervocalic}.
	 *
	 * @param s   input buffer
	 * @param len current length
	 */
	private static void markIntervocalic(@Nonnull char[] s, int len) {
		for (int i = 1; i < len - 1; i++) {
			if ((s[i] == 'i' || s[i] == 'u') && isVowel(s[i - 1]) && isVowel(s[i + 1])) {
				s[i] = Character.toUpperCase(s[i]);
			}
		}
	}

	/**
	 * Reverts the markers set by {@link #markIntervocalic} — the Snowball postlude.
	 *
	 * @param s   input buffer
	 * @param len current length
	 */
	private static void unmarkIntervocalic(@Nonnull char[] s, int len) {
		for (int i = 0; i < len; i++) {
			if (s[i] == 'I' || s[i] == 'U') {
				s[i] = Character.toLowerCase(s[i]);
			}
		}
	}

	/**
	 * Computes the RV region start, ported from the Snowball `mark_regions`: after the second letter when the
	 * word starts vowel-consonant; otherwise after the first vowel-to-consonant or consonant-to-vowel
	 * transition, whichever pattern applies.
	 *
	 * @param s   input buffer
	 * @param len current length
	 * @return start position of RV, or `len` when the word has no RV
	 */
	private static int markRV(@Nonnull char[] s, int len) {
		if (len < 2) {
			return len;
		}
		if (isVowel(s[0])) {
			if (!isVowel(s[1])) {
				// vowel + consonant: RV starts after the next vowel
				for (int i = 2; i < len; i++) {
					if (isVowel(s[i])) {
						return i + 1;
					}
				}
				return len;
			}
			// vowel + vowel: RV starts after the next consonant
			for (int i = 2; i < len; i++) {
				if (!isVowel(s[i])) {
					return i + 1;
				}
			}
			return len;
		}
		if (!isVowel(s[1])) {
			// consonant + consonant: RV starts after the next vowel
			for (int i = 2; i < len; i++) {
				if (isVowel(s[i])) {
					return i + 1;
				}
			}
			return len;
		}
		// consonant + vowel: RV starts at the third letter, matching the original's cursor arithmetic
		return len > 2 ? 3 : len;
	}

	/**
	 * Computes an R-region start: the position after the first vowel-followed-by-consonant found at or after
	 * `from` — R1 when called with 0, R2 when called with R1.
	 *
	 * @param s    input buffer
	 * @param len  current length
	 * @param from position to start scanning at
	 * @return start position of the region, or `len` when there is none
	 */
	private static int markAfterVowelConsonant(@Nonnull char[] s, int len, int from) {
		for (int i = from; i < len - 1; i++) {
			if (isVowel(s[i]) && !isVowel(s[i + 1])) {
				return i + 2;
			}
		}
		return len;
	}

	/**
	 * Tells whether the character is a folded Romanian vowel. The intervocalic markers `I`/`U` are deliberately
	 * not vowels — that is their purpose.
	 *
	 * @param c character to test
	 * @return true for `a`, `e`, `i`, `o`, `u`
	 */
	private static boolean isVowel(char c) {
		return c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u';
	}

	/**
	 * Applies the step-0 table (plural/article endings, R1-gated).
	 *
	 * @param s   input buffer
	 * @param len current length
	 * @param p1  R1 start
	 * @return length after the step
	 */
	private static int step0(@Nonnull char[] s, int len, int p1) {
		for (final Ending ending : STEP0_ENDINGS) {
			final int pos = len - ending.suffix().length();
			if (pos >= 0 && regionMatches(s, pos, ending.suffix())) {
				if (p1 > pos) {
					return len;
				}
				switch (ending.action()) {
					case 1:
						return pos;
					case 2:
						s[pos] = 'a';
						return pos + 1;
					case 3:
						s[pos] = 'e';
						return pos + 1;
					case 4:
						s[pos] = 'i';
						return pos + 1;
					case 5:
						// `ile` is kept when it follows `ab` (abile is derivational, not a plural)
						if (pos >= 2 && s[pos - 2] == 'a' && s[pos - 1] == 'b') {
							return len;
						}
						s[pos] = 'i';
						return pos + 1;
					case 6:
						s[pos] = 'a';
						s[pos + 1] = 't';
						return pos + 2;
					case 7:
						s[pos] = 'a';
						s[pos + 1] = 't';
						s[pos + 2] = 'i';
						return pos + 3;
					default:
						throw new IllegalStateException("Unknown step-0 action " + ending.action() + ".");
				}
			}
		}
		return len;
	}

	/**
	 * Applies one round of the combo-suffix table (derivational chains, R1-gated). The caller repeats it until
	 * it no longer reduces the length, as the original does.
	 *
	 * @param s   input buffer
	 * @param len current length
	 * @param p1  R1 start
	 * @return length after the round; unchanged when nothing fired
	 */
	private static int comboSuffix(@Nonnull char[] s, int len, int p1) {
		for (final Ending ending : COMBO_ENDINGS) {
			final int pos = len - ending.suffix().length();
			if (pos >= 0 && regionMatches(s, pos, ending.suffix())) {
				if (p1 > pos) {
					// Snowball aborts here; the port falls through to shorter entries instead, because folding
					// creates entry pairs the accented tables never both match (`picator` hits `icator` whose
					// accented source `icător` does not exist, blocking the `ator` the accented side took) -
					// found by the ro_RO lexicon sweep
					continue;
				}
				final String replacement = switch (ending.action()) {
					case 1 -> "abil";
					case 2 -> "ibil";
					case 3 -> "iv";
					case 4 -> "ic";
					case 5 -> "at";
					case 6 -> "it";
					default -> throw new IllegalStateException(
						"Unknown combo action " + ending.action() + "."
					);
				};
				for (int i = 0; i < replacement.length(); i++) {
					s[pos + i] = replacement.charAt(i);
				}
				return pos + replacement.length();
			}
		}
		return len;
	}

	/**
	 * Applies the standard-suffix table (R2-gated), including the `ţ`→`t` rewrite of `iune`/`iuni` behind the
	 * {@link #tiuneRewrite} switch.
	 *
	 * @param s   input buffer
	 * @param len current length
	 * @param p2  R2 start
	 * @return the new length when a rule fired — possibly equal to `len`, the `ist`→`ist` rewrite changes
	 *         nothing yet still suppresses the verb step — or -1 when nothing fired
	 */
	private int standardSuffix(@Nonnull char[] s, int len, int p2) {
		for (final Ending ending : STANDARD_ENDINGS) {
			final int pos = len - ending.suffix().length();
			if (pos >= 0 && regionMatches(s, pos, ending.suffix())) {
				if (p2 > pos) {
					// fall through to shorter entries - see comboSuffix on why the port backtracks where
					// Snowball aborts
					continue;
				}
				switch (ending.action()) {
					case 1:
						return pos;
					case 2:
						// the original requires a literal `ţ` before iune/iuni and rewrites it to `t`; folded,
						// the requirement reads `t` and the rewrite is the identity - i.e. the suffix after the
						// `t` is deleted. Without the switch the rule fails exactly as it does on a genuine `t`
						// in accented space.
						if (this.tiuneRewrite && pos > 0 && s[pos - 1] == 't') {
							return pos;
						}
						return -1;
					case 3:
						s[pos] = 'i';
						s[pos + 1] = 's';
						s[pos + 2] = 't';
						return pos + 3;
					default:
						throw new IllegalStateException(
							"Unknown standard-suffix action " + ending.action() + "."
						);
				}
			}
		}
		return -1;
	}

	/**
	 * Applies the verb-suffix table. Both the suffix and, for the conditional entries, the character before it
	 * must lie inside RV, mirroring the original's `limit_backward = I_pV`.
	 *
	 * @param s   input buffer
	 * @param len current length
	 * @param pV  RV start
	 * @return length after the step; unchanged when nothing fired
	 */
	private int verbSuffix(@Nonnull char[] s, int len, int pV) {
		for (final Ending ending : this.verbEndings) {
			final int pos = len - ending.suffix().length();
			if (pos >= 0 && regionMatches(s, pos, ending.suffix())) {
				if (pos < pV) {
					// the original matches inside a window clamped to RV (`limit_backward = I_pV`), so an entry
					// reaching below RV is simply not a match and shorter entries are still tried - fixed after
					// the ro_RO lexicon sweep caught the abort (`barati`: `arati` reaches below RV, `ati` fits)
					continue;
				}
				if (ending.action() == 1) {
					// delete only after a non-vowel or after `u`, and that character must sit inside RV too;
					// on failure fall through to shorter entries (`zgaurati` hits `urati` whose condition
					// fails, blocking the `ati` the accented side took) - see comboSuffix
					if (pos > pV && (!isVowel(s[pos - 1]) || s[pos - 1] == 'u')) {
						return pos;
					}
					continue;
				}
				return pos;
			}
		}
		return len;
	}

	/**
	 * Applies the final-vowel table (RV-gated).
	 *
	 * @param s   input buffer
	 * @param len current length
	 * @param pV  RV start
	 * @return length after the step; unchanged when nothing fired
	 */
	private static int vowelSuffix(@Nonnull char[] s, int len, int pV) {
		for (final Ending ending : VOWEL_ENDINGS) {
			final int pos = len - ending.suffix().length();
			if (pos >= 0 && regionMatches(s, pos, ending.suffix())) {
				if (pos < pV) {
					return len;
				}
				return pos;
			}
		}
		return len;
	}

	/**
	 * Tells whether the buffer carries `suffix` starting at `pos`.
	 *
	 * @param s      input buffer
	 * @param pos    position the suffix would start at
	 * @param suffix suffix text
	 * @return true when the characters match exactly
	 */
	private static boolean regionMatches(@Nonnull char[] s, int pos, @Nonnull String suffix) {
		for (int i = 0; i < suffix.length(); i++) {
			if (s[pos + i] != suffix.charAt(i)) {
				return false;
			}
		}
		return true;
	}

}
