{
  "filterBy" : {
    "attributeCodeInSet" : [
      "garmin-fenix-6-solar",
      "garmin-approach-s42-2",
      "garmin-vivomove-luxe",
      "garmin-vivomove-luxe-2"
    ]
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ]
    }
  }
}