global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    metrics_path: /observability/metrics
    static_configs:
      - targets: ['host.docker.internal:5557']
  - job_name: tempo
    static_configs:
      - targets: [ 'tempo:3200' ]