POST /rest/evita/Product/query

{
  "filterBy": {
    "hierarchyCategoriesWithin": {
      "ofParent": {
        "attributeUrlEquals": "/local-food"
      }
    },
    "entityLocaleEquals": "cs",
    "priceValidInNow": true,
    "priceInCurrency": "CZK",
    "priceInPriceLists": ["vip", "loyal-customer", "regular-prices"],
    "userFilter": [{
      "facetParameterValuesHaving": [{
        "entityHaving": {
          "attributeCodeInSet": ["gluten-free", "original-recipe"]
        }
      }],
      "priceBetween": ["600", "1600"]
    }]
  },
  "orderBy": [{
    "attributeCodeNatural": "ASC"
  }],
  "require": {
    "entityFetch": {
      "attributeContent": ["code"],
      "referenceCategoriesContent": {}
    },
    "facetSummary": {
      "statisticsDepth": "COUNTS"
    },
    "priceHistogram": {
      "requestedBucketCount" : 30,
      "behavior" : "STANDARD"
	}
  }
}