POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "audio"
      }
    }
  },
  "require" : {
    "hierarchyCategoriesOfReference" : {
      "requirements" : [
        {
          "fromRoot" : {
            "outputName" : "megaMenu",
            "entityFetch" : {
              "attributeContent" : [
                "code"
              ]
            },
            "requirements" : {
              "stopAt" : {
                "level" : 2
              }
            }
          }
        }
      ]
    }
  }
}