POST /rest/evita/product/query

{
  "filterBy" : {
    "referenceGroupsHaving" : [
      {
        "entityHaving" : {
          "attributeCodeEquals" : "sale"
        }
      }
    ]
  },
  "orderBy" : [
    {
      "referenceGroupsProperty" : [
        {
          "attributeOrderInGroupNatural" : "ASC"
        }
      ]
    }
  ],
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceGroupsContentWithAttributes" : {
        "attributeContent" : [
          "orderInGroup"
        ]
      }
    }
  }
}