POST /rest/evita/Product/query

{
  "filterBy" : {
    "referenceBrandHaving" : [
      {
        "entityHaving" : {
          "attributeCodeInSet" : [
            "sale",
            "new"
          ]
        }
      }
    ]
  },
  "orderBy" : [
    {
      "referenceGroupsProperty" : [
        {
          "attributeOrderInGroupNatural" : "ASC"
        }
      ]
    }
  ],
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceGroupsContentWithAttributes" : {
        "attributeContent" : [
          "orderInGroup"
        ]
      }
    }
  }
}