POST /rest/evita/Product/query

{
  "filterBy" : {
    "hierarchyCategoriesWithin" : {
      "ofParent" : {
        "attributeCodeEquals" : "accessories"
      }
    }
  },
  "orderBy" : [
    {
      "referenceCategoriesProperty" : [
        {
          "traverseByEntityProperty" : {
            "traversalMode" : "BREADTH_FIRST",
            "orderBy" : [
              {
                "entityPrimaryKeyNatural" : "ASC"
              }
            ]
          }
        },
        {
          "attributeOrderInCategoryNatural" : "ASC"
        }
      ]
    }
  ],
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ],
      "referenceCategoriesContentWithAttributes" : {
        "attributeContent" : [
          "orderInCategory"
        ]
      }
    }
  }
}