/*
 *
 *                         _ _        ____  ____
 *               _____   _(_) |_ __ _|  _ \| __ )
 *              / _ \ \ / / | __/ _` | | | |  _ \
 *             |  __/\ V /| | || (_| | |_| | |_) |
 *              \___| \_/ |_|\__\__,_|____/|____/
 *
 *   Copyright (c) 2026
 *
 *   Licensed under the Business Source License, Version 1.1 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   https://github.com/FgForrest/evitaDB/blob/master/LICENSE
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */


package io.evitadb.externalApi.grpc.requestResponse;

import io.evitadb.api.requestResponse.schema.AttributeFilterAccelerator;
import io.evitadb.exception.EvitaInvalidUsageException;
import io.evitadb.externalApi.grpc.generated.GrpcAttributeFilterAccelerator;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

import javax.annotation.Nonnull;

import static io.evitadb.test.TestTags.ATTRIBUTE;
import static io.evitadb.test.TestTags.EXTERNAL_API;
import static io.evitadb.test.TestTags.GRPC;
import static io.evitadb.test.TestTags.SCHEMA;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Verifies the filter accelerator enum mapping in {@link EvitaEnumConverter}. The happy-path mapping is already
 * exercised indirectly by the schema and mutation converter round-trips; this test covers the one thing those
 * structurally cannot reach - the defensive throw branch. A round trip only ever feeds the converter values the
 * converter itself produced, so neither the proto3 zero nor a value from a newer peer is ever generated by one, and
 * both are exactly the inputs that must fail loudly rather than decode as an arbitrary accelerator.
 *
 * @author Jan Novotný (novotny@fg.cz), FG Forrest a.s. (c) 2026
 */
@DisplayName("EvitaEnumConverter filter accelerator mapping")
@Tag(GRPC)
@Tag(EXTERNAL_API)
@Tag(SCHEMA)
@Tag(ATTRIBUTE)
class EvitaEnumConverterAcceleratorTest {

	@Test
	@DisplayName("should reject an unrecognized remote filter accelerator")
	void shouldThrowWhenAcceleratorIsUnrecognized() {
		// the value a NEWER peer sends for an accelerator this build has never heard of - decoding it as anything at
		// all would silently maintain the wrong index, so it has to be refused
		assertThrows(
			EvitaInvalidUsageException.class,
			() -> EvitaEnumConverter.toAttributeFilterAccelerator(GrpcAttributeFilterAccelerator.UNRECOGNIZED)
		);
	}

	@Test
	@DisplayName("should reject the unspecified default, which proto3 supplies for an unset field")
	void shouldThrowWhenAcceleratorIsUnspecified() {
		// proto3 has no field presence for enums, so a client that forgets to set the value sends the zero. Absence
		// of an acceleration is expressed by an empty `accelerators` list, never by this member, which makes an
		// explicit zero on the wire always a client mistake rather than a default worth honouring
		assertThrows(
			EvitaInvalidUsageException.class,
			() -> EvitaEnumConverter.toAttributeFilterAccelerator(
				GrpcAttributeFilterAccelerator.ATTRIBUTE_FILTER_ACCELERATOR_UNSPECIFIED
			)
		);
	}

	@ParameterizedTest
	@EnumSource(AttributeFilterAccelerator.class)
	@DisplayName("should round-trip every declared filter accelerator")
	void shouldRoundTripEveryAccelerator(@Nonnull AttributeFilterAccelerator accelerator) {
		// exhaustive rather than hardcoding SUBSTRING_SEARCH: a future constant added to the domain enum without
		// teaching the converter about it fails here as well as at the converter's own exhaustive switch
		assertEquals(
			accelerator,
			EvitaEnumConverter.toAttributeFilterAccelerator(
				EvitaEnumConverter.toGrpcAttributeFilterAccelerator(accelerator)
			)
		);
	}
}
