POST /rest/evita/category/query

{
  "filterBy" : {
    "hierarchyWithinRootSelf" : {
      "directRelation" : true
    }
  },
  "require" : {
    "entityFetch" : {
      "attributeContent" : [
        "code"
      ]
    }
  }
}