name: Kubernetes-benchmark-cleanup

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  do-benchmark-clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0 checkout sources

      - name: Install doctl
        uses: digitalocean/action-doctl@135ac0aa0eed4437d547c6f12c364d3006b42824 # v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run clean-benchmark
        env:
          LIMIT_HOURS : 24
        run: |
          export DO_CLUSTER_BENCHMARK_NAME="${DO_CLUSTER_NAME}-memory"
          ./evita_performance_tests/src/do_k8s_automation/deploy/101-safety_kill.sh
