name: Kubernetes-benchmark-cleanup

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  do-benchmark-clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0 checkout sources
        with:
          persist-credentials: false

      - name: Install doctl
        uses: digitalocean/action-doctl@3cb3953159719656269e044e0e24ca16dd2a690f # v2.5.2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run clean-benchmark
        env:
          LIMIT_HOURS : 24
        run: |
          export DO_CLUSTER_BENCHMARK_NAME="${DO_CLUSTER_NAME}-memory"
          ./evita_test/evita_performance_tests/src/do_k8s_automation/deploy/101-safety_kill.sh
