# Main build pipeline, operates on `dev` branch which is our integration branch

name: CI Dev branch

on:
  push:
    branches: [ "dev" ]            # trap each push to dev branch
    paths:                         # but react only to changes in code or pipeline definition
      - evita*/**/*.java
      - evita*/**/pom.xml
      - pom.xml
      - evita_external_api/evita_external_api_lab/src/main/resources/META-INF/lab/gui/dist/**
      - jacoco/**/pom.xml
      - docker/**
      - .github/**

permissions:
  contents: write
  actions: read
  checks: write

concurrency:
  group: ${{ github.ref_name }}                      # for the same branch (dev)
  cancel-in-progress: true        # run only one workflow at a time (cancel the previous)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1 checkout sources
      with:
        persist-credentials: false

    - name: Setup Java JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.1.0  # setup JDK 17 for building
      with:
         distribution: 'temurin'
         java-version: '17'
         cache: 'maven'
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_CENTRAL_TOKEN
         gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
         gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Build with Maven       # run Maven with tests
      run: |
        mvn -T 1C -B package -P unitAndFunctional jacoco:report-aggregate -V --fail-at-end -Dmaven.test.skip=false --file pom.xml
        jacoco/jacoco-summary.sh jacoco/target/site/jacoco-aggregate/jacoco.csv

    - name: Upload test results    # upload XML with unit test results for debugging
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: success() || failure()
      with:
        name: test-results
        path: 'evita*/**/target/surefire-reports/TEST-*.xml'

    - name: Publish Test Report
      uses: ./.github/actions/publish-test-report
      if: success() || failure()

    - name: Upload evitaDB server artifact   # upload `evita-server.jar` for `docker-canary.yml` to deploy to DockerHub
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: success()
      with:
        name: evita-server.jar
        path: 'evita_server/target/evita-server.jar'

    - name: Upload coverage to Codecov    # upload code coverage from Jacoco to codecov
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8 # v5.0.0

    - name: Deploy with Maven       # deploy SNAPSHOTS to Maven repository
      run: |
        mvn -T 1C -B javadoc:jar source:jar deploy -DdeployAtEnd=true -Dmaven.test.skip=true --file pom.xml
      continue-on-error: true
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
