# This job builds and deploys Docker image to DockerHub

name: DockerHub-deploy-canary

on:
  workflow_run:
    workflows: ['CI Dev branch']                     # runs after CI workflow
    types:
      - completed

permissions:
  contents: read          # Required for actions/checkout to read the repository
  actions: read           # Required to download artifacts from the triggering workflow
  packages: write         # Required for pushing Docker images to DockerHub

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2        # checkout from Git
        with:
          ref: dev  # Always checks out the dev branch

      - name: Download a single artifact # download `evita-server.jar` artifact if the workflow we react to was successful
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: evita-server.jar
          path: docker

      - name: Set up QEMU
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3

      - name: Configure QEMU
        # Configure QEMU for Docker Buildx, see https://github.com/docker/buildx/issues/1170#issuecomment-2424530330
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          buildkitd-flags: --debug
          platforms: linux/amd64,linux/arm64/v8

      - name: Login to DockerHub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ vars.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        env:
          RELEASE_IMAGE: "evitadb:canary"
          EVITA_JAR_NAME: evita-server.jar
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        with:
          context: ./docker
          file: ./docker/Dockerfile
          pull: true
          push: true
          tags: ${{ vars.CI_REGISTRY_USER }}/${{ env.RELEASE_IMAGE }}
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            EVITA_JAR_NAME=${{ env.EVITA_JAR_NAME }}       
