# Nightly job, that should execute all tests (including long-running ones) when something was committed.
name: All tests including long-running

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 1' # runs on Monday morning

permissions:
  contents: read      # Required for actions/checkout to fetch the repository code.
  actions: read       # Required for the workflow to use the actions/checkout action.
  checks: write       # Required for the workflow to create check runs.
  statuses: write     # Required for the workflow to update commit statuses.

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [X64]
        include:
          - os: ubuntu-latest
            arch: ARM64
          - os: macos-latest
            arch: ARM64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      # inspiration from https://github.com/nvim-neorocks/luarocks-tag-release#version-optional
      - name: Get new commits   # initialize github env variable with count of commits in the dev branch in the last week
        shell: bash
        run: |
          git fetch origin dev
          echo "NEW_COMMIT_COUNT=$(git log --oneline --since '168 hours ago' origin/dev | wc -l)" >> $GITHUB_ENV
          echo "Commits found in dev branch: $NEW_COMMIT_COUNT"

      - name: Setup Java JDK   # this should setup JDK 17 but only if something was committed to dev branch in the last week
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        if: ${{ env.NEW_COMMIT_COUNT != '0' }}
        with:
           distribution: 'temurin'
           java-version: '17'
           cache: 'maven'

      - name: Long running tests   # this run Maven tests but only if something was committed to dev branch in the last week
        if: ${{ env.NEW_COMMIT_COUNT != '0' }}
        run: mvn -T 1C -B package -P longRunning -V --fail-at-end --file pom.xml

      - name: Upload test results  # this upload test results but only if something was committed to dev branch in the last week
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        if: ${{ env.NEW_COMMIT_COUNT != '0' && always() }}
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.arch }}
          path: 'evita*/**/target/surefire-reports/TEST-*.xml'
