# Nightly job, that should execute all tests (including long-running ones) when something was committed.
name: All tests including long-running

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 1' # runs on Monday morning

permissions:
  contents: read      # Required for actions/checkout to fetch the repository code.
  checks: write       # Required for the workflow to create check runs.

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [X64]
        include:
          - os: ubuntu-latest
            arch: ARM64
          - os: macos-latest
            arch: ARM64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          persist-credentials: false

      # inspiration from https://github.com/nvim-neorocks/luarocks-tag-release#version-optional
      - name: Get new commits   # initialize github env variable with count of commits in the dev branch in the last week
        shell: bash
        run: |
          git fetch origin dev
          COMMIT_COUNT=$(git log --oneline --since '168 hours ago' origin/dev | wc -l)
          echo "NEW_COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "Commits found in dev branch: $COMMIT_COUNT"

      - name: Setup Java JDK   # this should setup JDK 17 but only if something was committed to dev branch in the last week
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0  # setup JDK 17 for building
        if: ${{ env.NEW_COMMIT_COUNT != '0' }}
        with:
           distribution: 'temurin'
           java-version: '17'
           cache: 'maven'

      - name: Long running tests   # this run Maven tests but only if something was committed to dev branch in the last week
        if: ${{ env.NEW_COMMIT_COUNT != '0' }}
        run: mvn -T 1C -B package -P longRunning -V --fail-at-end --file pom.xml

      - name: Upload test results  # this upload test results but only if something was committed to dev branch in the last week
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ env.NEW_COMMIT_COUNT != '0' && always() }}
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.arch }}
          path: 'evita*/**/target/surefire-reports/TEST-*.xml'

      - name: Publish Test Report
        uses: ./.github/actions/publish-test-report
        if: ${{ env.NEW_COMMIT_COUNT != '0' && always() }}
