# This job notifies internal Mattermost channel about the release

name: Notify Mattermost on Release

on:
  release:
    types: [published]

jobs:
  notify:
    # Ensure we only have read access to the repo
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Preprocess the release body to escape newlines and set as an output variable
      - name: Prepare Release Body
        id: prepare_body
        run: |
          sanitized_body=$(printf '%s' "${{ github.event.release.body }}" | sed ':a;N;$!ba;s/\n/\\n/g')          
          echo "name=processed_body::$sanitized_body" >> $GITHUB_OUTPUT

      # Send the message to Mattermost with the escaped release body
      - name: Send message to Mattermost
        uses: mattermost/action-mattermost-notify@b7d118e440bf2749cd18a4a8c88e7092e696257a # v2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          PAYLOAD: |-
            {
              "text": "## 🎉 evitaDB ${{ github.event.release.tag_name }} released!\n\n${{ steps.prepare_body.outputs.processed_body }}",
              "color": "#31bf2c",
              "username": "${{ github.triggering_actor }}",
              "icon": "https://raw.githubusercontent.com/FgForrest/evitaDB/dev/documentation/assets/img/evita.png"
            }